### ISSUE TITLE
GVFS.Mount leaks file descriptors in HandleRecursivelyEnumerateDirectoryRequest and RecursivelyMarkAllChildrenAsInRoot

### ISSUE THREAD

**Issue by nickgra** [Microsoft/VFSForGit#1037]
While standing up the Large Repo Perf Tests on macOS, I noticed that my machine was running out of file descriptors after running a test where thousands of placeholders (files and directories) are created and then deleted. GVFS.Mount had a bunch of file descriptors open for folders that were already deleted. 

We have the same bug in two code paths, `HandleRecursivelyEnumerateDirectoryRequest` and `RecursivelyMarkAllChildrenAsInRoot` both walk a directory structure but only call `closedir` on the parent directory.

**Comment by wilbaker** [comment]
@nickgra FYI I took the `domain:kext` label off because this bug is in user-mode.

/cc: @jrbriggs, do you think we should use the kext label for native user-mode issues?
