### ISSUE TITLE
GitHub VFSForGit Mac Large Repo Perf Tests should run against release build of VFS4G

### ISSUE THREAD

**Issue by wilbaker** [Microsoft/VFSForGit#1066]
The "GitHub VFSForGit Mac Large Repo Perf Tests" build is currently using a debug build of VFS4G, and it should use a release version like we do on Windows.

**Comment by nickgra** [comment]
This is done: https://dev.azure.com/mseng/AzureDevOps/_build/results?buildId=9338228&_a=summary
