### ISSUE TITLE
GVFS should clean up resources when CompleteCommand returns HRESULT_FROM_WIN32( ERROR_OPERATION_ABORTED )

### ISSUE THREAD

**Issue by wilbaker** [Microsoft/VFSForGit#107]
If CompleteCommand returns HRESULT_FROM_WIN32( ERROR_OPERATION_ABORTED ) when GVFS is completing a StartDirectoryEnumeration callback, GVFS should clean up the resources associated with the enumeration.

**Comment by wilbaker** [comment]
@cgallred I just found this old issue filed against VFS4G.

With the recent managed API changes, can we still get  `HRESULT_FROM_WIN32( ERROR_OPERATION_ABORTED )` when calling `CompleteCommand`?  If not, what HRESULT value should we check for (or is this scenario no longer possible)?

**Comment by cgallred** [comment]
@wilbaker nothing in the managed API changes would have changed how `CompleteCommand` behaves with respect to `StartDirectoryEnumeration`.  Besides, from looking at the ProjFS driver/lib code I don't see how we might return that error from `CompleteCommand`.

Instead if the user cancelled the enumeration then your `CancelCommandCallback` would be invoked with the `commandId` that was given to your `StartDirectoryEnumerationCallback`.  Even then we'd still send you an `EndDirectoryEnumerationCallback`.  Note that we still have the potential race where if an enumeration gets cancelled you _might_ see the `EndDirectoryEnumerationCallback` out of order with a `GetDirectoryEnumerationCallback`.

**Comment by wilbaker** [comment]
@cgallred thanks for the details!  I couldn't find much in my notes/email on the history of this issue.  I'll go ahead and close this.
