### ISSUE TITLE
question: how to implement the fine-grained access control in the git server?

### ISSUE THREAD

**Issue by hawkingrei** [Microsoft/VFSForGit#1075]
Hi! We are using mono repo for our developing work. so we want to use VFSForGit to solve fine-grained access control.  but when I read the document about GVFS protocol, I find that it is lack of information on how to reply the request without permission to a single file or folder? Can my git server reply 401 to VFSForGit ？

**Comment by jrbriggs** [comment]
This is a common question with VFS for Git, but it not supported and not planned. VFS for Git is designed to only solve perf and scale problems of extremely large monorepos and does not attempt to add new features to Git.

Using Git, anyone that has access to the repository can access any file that has ever existed in the repository. VFS for Git will not change that.

**Comment by hawkingrei** [comment]
Thank you.
