### ISSUE TITLE
Mac: Large Repo Perf Tests are frequently hanging

### ISSUE THREAD

**Issue by wilbaker** [microsoft/VFSForGit#1077]
@jeschu1 has started the process of adding more logging to track down where the hangs are happening, most recent update:

>On Console we saw many lines saying “NO RESPONSE AFTER”, with 2.5 hour lags.
We also attached to the mount and didn’t see any requests processing (everything waiting on tryTake from the network file operation queue).
> 
>This makes us think either
>- Messages never reached the mount processed
>- Mount process failed to respond

**Comment by jeschu1** [comment]
This was resolved by upgrading the build machine to Mojave
