### ISSUE TITLE
LooseObjectStep may fail due to corrupt loose object

### ISSUE THREAD

**Issue by derrickstolee** [microsoft/VFSForGit#1079]
During the `LooseObjectStep`, we can hit an issue where our loose object is corrupt. We don't respond well, and will continue retrying on every execution:

```
error: inflate: data stream error (unknown compression method)
error: unable to unpack {oid} header
error: inflate: data stream error (unknown compression method)
error: unable to unpack {oid} header
fatal: loose object {oid} (stored in {path}\gitObjects/{??}/{oid}) is corrupt
```

We could try to respond to this error by parsing the output and deleting the specific loose object. Perhaps we could make Git more resilient and have it delete the object and continue if corrupt. This would be a behavior change, as normally `git pack-objects` really _should_ fail if a given object can't be added to the pack.

**Comment by jrbriggs** [comment]
@derrickstolee how frequently have we seen this?

**Comment by derrickstolee** [comment]
I saw it once, and contacted the user with the problem (haven’t heard back). I can keep an eye out for the issue, or even create an alert to notify us. 

The biggest concern is that we don’t auto-correct ourselves and the step will keep failing without making progress.

**Comment by derrickstolee** [comment]
More users are hitting this than I thought.
