### ISSUE TITLE
Mac: The installer should use the published version of GVFS.Service rather than `dotnet GVFS.Service.dll`

### ISSUE THREAD

**Issue by wilbaker** [Microsoft/VFSForGit#1095]
Currently the GVFS.Service is being launched using `dotnet GVFS.Service.dll`:

https://github.com/Microsoft/VFSForGit/blob/2d37c40e2b2b7cb51a2b87681decae8c8e6db2d8/GVFS/GVFS.Service/Mac/org.vfsforgit.service.plist#L22

And it should be launching the published version of GVFS.Service

**Comment by jrbriggs** [comment]
@alameenshah can you take a look at this to unblock the release to EA?
