### ISSUE TITLE
Virtualize just the worktree, not the git database (for local-only usage)

### ISSUE THREAD

**Issue by mehrdadn** [Microsoft/VFSForGit#1099]
Are there any plans to make it possible to virtualize just the worktree, while using the physically present git databases? (i.e. without involving any remote server at all?)

This would be extremely useful since git databases are inherently compressed/deduplicated, and it's helpful able to browse them like normal folders without checking out many large files into a physical worktree.

**Comment by jrbriggs** [comment]
No, this is not planned. VFS for Git's primary use case is for monorepos that are far too large to have entirely locally, so this would be contrary to the project's goals of enabling those repositories.

**Comment by jrbriggs** [comment]
I believe this question has been answered, so I'm closing this issue.
