### ISSUE TITLE
Querying remote for config...Failed

### ISSUE THREAD

**Issue by tan234tan** [Microsoft/VFSForGit#1100]
Hello,
I am trying to use gvfs to clone a plastic SCM repo. I have already enabled gitserver function on my plastic SCM server, and git clone http://myserver/repo is ok.
But if I use gvfs to clone this repo, it shows the following error message: Querying remote for config...Failed.
I have checking the following:
a .gitattributes file on my repo with content * -text
telnet myserver 9000 is working
disabled selinux on my server
Would anyone can figure it out? 
Thank you very much.

$ gvfs clone http://plastic_test:8001/default
Clone parameters:
  Repo URL:     http://plastic_test:8001/default
  Branch:       Default
  Cache Server: Default
  Local Cache:  C:\.gvfsCache
  Destination:  C:\Users\wxtan\test3\default
Authenticating...Succeeded
Querying remote for config...Failed
Unable to query /gvfs/config
Server returned error code 500 (InternalServerError). Original error message from server:

**Comment by jrbriggs** [comment]
VFS for Git relies on a [custom protocol](https://github.com/Microsoft/VFSForGit/blob/master/Protocol.md). I don't think Plastic SCM supports those API extensions, so I would expect this to fail.

If you're interested in trying VFS for Git, you can push the repository to Azure DevOps, which does support the protocol.

**Comment by jrbriggs** [comment]
I believe this question is answered, so I'm closing out the issue.
