### ISSUE TITLE
Mac: Determine if placeholders need to be created to file size

### ISSUE THREAD

**Issue by jeschu1** [microsoft/VFSForGit#1133]
Since we hydrate on KAUTH_VNODE_READ_ATTRIBUTES and stat(), calls  KAUTH_VNODE_READ_ATTRIBUTES | KAUTH_VNODE_READ_SECURITY, this seems unnecessary.  

Credit to @pmj for finding the reference https://github.com/apple/darwin-xnu/blob/a449c6a3b8014d9406c2ddbdc81795da24aa7443/bsd/vfs/vfs_vnops.c#L1446

**Comment by jeschu1** [comment]
Testing thus far hasn't found issues with removing the code to make placeholders match filesize.

I built a standalone application to measure the cost of creating placeholders.
For 1,000,000 files of 30K the cost of making placeholders match filesize was 25 seconds.

We'd expect to see a performance improvement when
- Doing a checkout for any placeholder file that has changed
- Transversing a directory without hydration "ls -r"

@kewillford for reference

**Comment by wilbaker** [comment]
\+ @pmj as well

**Comment by pmj** [comment]
> I built a standalone application to measure the cost of creating placeholders.
> For 1,000,000 files of 30K the cost of making placeholders match filesize was 25 seconds.

I take it this was *just* creating placeholders, not subsequently hydrating? Did you have a chance to find out if not sizing the placeholders then caused hydration to take longer? This was one hypothesis for why your overall "large build" tests didn't seem to change in runtime when not sizing placeholders.

A few more pieces of info that would be interesting: What filesystem(s)? Also, is the 25 seconds the difference in total runtime of creating 10<sup>6</sup> files, or is it the aggregate duration of all the `ftruncate()` calls?

**Comment by jeschu1** [comment]
> Did you have a chance to find out if not sizing the placeholders then caused subsequent hydration to take longer?

This *may* happen, but there are still many cases where you would make a placeholder but then not hydrate.  We can speed up that flow. 

> This was one hypothesis for why your overall "large build" tests didn't seem to change in runtime when not sizing placeholders.

@kewillford gave me a great brain dump of the large build tests and here's the summary.
We should have a speed up whenever we create a placeholder (but don't hydrate)
This happens when:
1. `ls -R` (this is a specific test in the perf tests)
2. checkout where you have many placeholders and those files have changed

The perf tests cover 1 and we do see a few seconds speedup there consistently.  
While the perf tests do checkouts, they don't do any with a significant amount of files changed.  Hence no speedup there.  We talked about adding an additional perf test showcasing this, but since 1 already hits this path probably unnecessary.

**Comment by pmj** [comment]
> This _may_ happen, but there are still many cases where you would make a placeholder but then not hydrate. We can speed up that flow.

Yeah, I'm not saying it's not worth doing - I'm just curious where that null result was coming from.
