### ISSUE TITLE
Mac: Debug Knowledge for the Kext

### ISSUE THREAD

**Issue by jeschu1** [microsoft/VFSForGit#1135]
We want to get to a point where we can comfortably debug the Kext.  

1. Is there a way to get a dump from a hang on a users machine?
2. Create a crash, debug that crash
3. Repeat 3 by trading the crash with your partner.  See if you can determine what caused the crash.  4. What questions do we have on the Ktruss script?

**Comment by jrbriggs** [comment]
Closing this out as I believe we've had a few exercises here.
