### ISSUE TITLE
Mac: Support directory hardlinks.

### ISSUE THREAD

**Issue by wilbaker** [microsoft/VFSForGit#1152]
- Unlike Windows, Mac supports directory hardlinks
- The kext needs to deliver notifications for directory hardlinks, and the VFS4G provider needs to react appropriately (design work required to determine how to appropriately react).

Related issue #337 is for supporting file hardlinks on Mac.

**Comment by jrbriggs** [comment]
Customer reports they have no dependency on directory hardlinks. Moving to the backlog to consider against other priorities.

/cc @wilbaker

**Comment by jrbriggs** [comment]
Closing for now to clear up the active issues. We'll reopen if more demand shows up.
