### ISSUE TITLE
Mac: Frequent hangs/stalls during functional tests

### ISSUE THREAD

**Issue by pmj** [microsoft/VFSForGit#1205]
Mac functional test runs have occasionally been hitting the timeout of 180 minutes over the last few weeks, but either I've been extremely unlucky or they've become more frequent recently.

I've re-queued PR #1200 a few times now, each time hitting either #1204 or the timeout problem. The changes in the PR itself only affect kext unit tests which complete without issue according to the logs.

Recent example:  https://dev.azure.com/mseng/AzureDevOps/_build/results?buildId=9557200&view=results (retained)

Previous runs seem to have disappeared from the log already, I have queued some new builds now and will retain and add them here if they time out.

As the functional tests [appear to still be running on macOS 10.13 (High Sierra)](https://github.com/microsoft/VFSForGit/pull/1193#issuecomment-495285780) could this be the kext-side IOSharedDataQueue issue yet again? (#161) If so, can we either upgrade the test runner machines or implement the kext-side workaround as well?

Note: #1165 may help with diagnosing this.

**Comment by pmj** [comment]
Another one:

https://dev.azure.com/mseng/AzureDevOps/_build/results?buildId=9571613&view=results

**Comment by pmj** [comment]
https://dev.azure.com/mseng/AzureDevOps/_build/results?buildId=9581752&view=results

**Comment by pmj** [comment]
https://dev.azure.com/mseng/AzureDevOps/_build/results?buildId=9583367&view=results

**Comment by pmj** [comment]
https://dev.azure.com/mseng/AzureDevOps/_build/results?buildId=9609994&view=results

**Comment by wilbaker** [comment]
@pmj if you notice this happen again when I'm online could you send me a message?  I'd like to to hop onto one of the machines while a hang is in progress.

**Comment by wilbaker** [comment]
Closed by #1273

**Comment by wilbaker** [comment]
(Fixed in master in #1276)
