### ISSUE TITLE
macOS installer: automount fails

### ISSUE THREAD

**Issue by jamill** [microsoft/VFSForGit#1210]
The macOS installer fails to re-mount repositories. The following error is contained in the service logs:

```"ErrorMessage":"LaunchProcess ERROR: Could not launch /bin/launchctl"}```

**Comment by jamill** [comment]
It looks like the problem is that the kext is not loaded after running the installer, which causes the launchctl command to fail to auto-mount the repositories.

If we run the launchctl command (that is run by the service to mount) manually, we see that we are prompted to load the kext. If we load the kext manually, and then restart the service, we see the enlistments get auto-mounted as expected.

**Comment by alameenshah** [comment]
@nickgra @kewillford @wilbaker @jrbriggs - please share your thoughts on updating the Mac installer to load the kext...

**Comment by alameenshah** [comment]
>>@alameenshah when is the kext normally loaded? Have we been requiring users to do this manually?

@pmj - IOKit kexts are supposed to get loaded automatically, right?

**Comment by kewillford** [comment]
@wilbaker @alameenshah  We have [code that will run during mount](https://github.com/microsoft/VFSForGit/blob/50ef886d3afe886d38c7e2add08b2590f9a3f320/GVFS/GVFS.Platform.Mac/ProjFSKext.cs#L93)

**Comment by alameenshah** [comment]
> @wilbaker @alameenshah We have [code that will run during mount](https://github.com/microsoft/VFSForGit/blob/50ef886d3afe886d38c7e2add08b2590f9a3f320/GVFS/GVFS.Platform.Mac/ProjFSKext.cs#L93)

This works when `gvfs mount` command is run interactively, right? 

Mac installer relies on `GVFS.Service` to do the auto-mount of registered repos. When `GVFS.Service` gets launched (post installation) it (`Service`) calls `gvfs mount` in the background (without user interaction). In this case if the kext is not loaded, then `mount` will fail. Updating the installer to load kext would help in scenario.

**Comment by wilbaker** [comment]
It sounds like we'll have to have the installer load the kext.  We want the auto-mount scenario to work when users upgrade.

**Comment by jrbriggs** [comment]
> It sounds like we'll have to have the installer load the kext. We want the auto-mount scenario to work when users upgrade.

I agree. I've been surprised a couple of times when I upgraded with the pkg then had to elevate during gvfs mount to get the kext loaded. Let's make the pkg responsible for attempting to load the kext.
