### ISSUE TITLE
Is it possible to use VFSForGit on Linux?

### ISSUE THREAD

**Issue by sharpaper** [microsoft/VFSForGit#1226]
I'm interested in this project but I don't see any support for Linux.

**Comment by chrisd8088** [comment]
Hi, and thanks for the question!  The short answer is that a Linux VFSForGit client is not yet available, but we're working on it!

To expand briefly on that short answer, GitHub engineers are collaborating with the Microsoft VFSForGit team to bring a Linux client to fruition.  The current state of this effort is visible in the [`features/linuxprototype` branch](https://github.com/microsoft/VFSForGit/tree/features/linuxprototype) of this repository; please note that development is ongoing and not yet complete, but is proceeding relatively quickly.

There are several dependencies required for anyone who wants to compile and run a test build the `features/linuxprototype` branch on a Linux system, notably the [libprojfs](https://github.com/github/libprojfs) Linux projected filesystem library, which has been developed in conjunction with the VFSForGit Linux client work.  Most of these dependencies are documented in the [Build and Installation Notes](https://github.com/github/libprojfs/blob/master/docs/build-install.md) for the libprojfs project; they include a [FUSE](https://www.kernel.org/doc/Documentation/filesystems/fuse.txt)-enabled kernel, a recent version of [libfuse v3](https://github.com/libfuse/libfuse), and the [.NET Core SDK](https://github.com/dotnet/core/blob/master/release-notes/download-archive.md#net-core-runtime-and-sdk-download-archive) for Linux.

In addition, as is the case for all VFSForGit clients (on macOS and Windows as well as Linux), a custom version of the Git client is required, built from the [microsoft/git](https://github.com/microsoft/git) fork of the [Git for Windows](https://github.com/git-for-windows/git) project, itself a fork of upstream [Git](https://github.com/git/git).  

As noted in the [VFSForGit Linux Client Design](https://github.com/github/libprojfs/blob/master/docs/design.md) page of the libprojfs project, FUSE is the basis of this current work, and has provided a sufficiently functional filesystem layer on which to port the existing VFSForGit codebase to Linux, shaking out lots of [small](github/VFSForGit#9) [issues](github/VFSForGit#29) along the way.  It remains possible, however, that FUSE could be supplanted in the future with some alternate combination of Linux filesystems and notification APIs, and if so, such a change would be abstracted behind the libprojfs API as much as possible.

Once again, thank you very much for the enquiry, and I hope this information is at least somewhat encouraging!

(See also the prior issue #4, and the [GitHub development-only fork](https://github.com/github/VFSForGit) of this repository.)

**Comment by jrbriggs** [comment]
Closing, as I believe this question has been answered. Thanks for the interest @sharpaper

**Comment by alan1975** [comment]
Hi, wanted to reopen this question as it’s been nearly 18mths since it was originally asked… 

Any progress/date for when Linux support for gfvs might be available?
