### ISSUE TITLE
Mac: KAUTH_FILEOP_RENAME delivers a different format for paths on Catalina

### ISSUE THREAD

**Issue by wilbaker** [microsoft/VFSForGit#1335]
On Catalina RENAME paths will start with `/System/Volumes/Data/Users` rather than `/Users`, and this is breaking `GetRelativePath` which expects the paths from the kext to start with `/Users`.

We should also investigate if there are changes to any other paths (e.g. `/usr`, `/tmp`)

**Comment by jeschu1** [comment]
@wilbaker since we have confirmation from Apple this is the right behavior and a fix on our side, I'm going to close
