### ISSUE TITLE
VFSForGit causes OS to hang when open VS solution with large amount of C# files.

### ISSUE THREAD

**Issue by nikola-sh** [microsoft/VFSForGit#1347]
Windows: 10.0.17763.615 or 10.0.18362.175
VFSForGit: 1.0.19157.1
     
Description:
    When VS finished loading solution it starts to process C# files by IntelliSense and sends too much requests to PrjFlt.
    As a result OS hangs sometimes, i.e. it can't start processes or open files.
    After some time OS crashes with stack
        00 nt!KeBugCheckEx
        01 nt!PopIrpWatchdogBugcheck
        02 nt!PopIrpWatchdog
        03 nt!KiProcessExpiredTimerList
        04 nt!KiRetireDpcList
        05 nt!KiIdleLoop

Repro steps:
    I have prepared utility to emulate VS behavior: GVFS.StressTester.exe (look into attach.zip)
    1. Prepare repository with 10000 files in `many_files` dir.
    2. Clone repository by VFSForGit to `c:\repo`
    3. Execute `gvfs prefetch --folders /many_files`
    4. Run `GVFS.StressTester.exe c:\repo\src\many_files 10000` 
    5. Expected that OS will hang: GVFS.StressTester.exe will not finish ever, processes will not start.
       If system doesn't hang execute `gvfs dehydrate --confirm c:\repo` and go to step 4.

System status:

~4000 threads in [System] with stack:
```
  00 nt!KiSwapContext
  01 nt!KiSwapThread
  02 nt!KiCommitThreadWait
  03 nt!KeWaitForMultipleObjects
  04 nt!FsRtlCancellableWaitForMultipleObjects
  05 FLTMGR!FltCancellableWaitForMultipleObjects
  06 prjflt!PrjfSendCommandAndWaitForCompletion
  07 prjflt!PrjfSendCommand
  08 prjflt!PrjfSendGetFileStreamCommand
  09 prjflt!PrjfCopyStreamData
  0a prjflt!PrjfExpandFile
  0b prjflt!PrjfExpansionWorker
  0c FLTMGR!FltpProcessGenericWorkItem
  0d nt!ExpWorkerThread
  0e nt!PspSystemThreadStartup
  0f nt!KiStartSystemThread
```

GVFS.Mount.exe stacks and logs are in attach.zip.

I can give a complete memory dump file if Microsoft engineer contact me.

[attach.zip](https://github.com/microsoft/VFSForGit/files/3423049/attach.zip)

**Comment by derrickstolee** [comment]
Hi @nikola-sh. It is expected that such an influx of filesystem calls could cause degraded performance. You could prevent this by adding `--hydrate` to your `gvfs prefetch --folders /many_files` call, as that will ensure those files are populated on disk before you open VS.
