### ISSUE TITLE
robocopy from gvfs dir outputs bad files

### ISSUE THREAD

**Issue by jamesford42** [Microsoft/VFSForGit#141]
I am using robocopy as part of my build process, for preparing content files in the working directory. These data files are checked. 

I have found that for files which I have not previously opened myself (and presumably thereby triggering gvfs to fully get the files contents) I will end up with a file the right size copied to output, but entirely filled with zeros.

Note that using xcopy instead of robocopy seems to work.

**Comment by sanoursa** [comment]
We have seen robocopy bugs in the past, though the issues that we know of are fixed. To help repro the issue, could you please provide the following?

* What versions of Windows and GVFS are you using?
* What are the paths involved? Are you moving files around within src, src->outside, or outside->src?
* Can you produce a minimal repro of the issue? It would be very helpful to have a specific robocopy command, and even better would be a procmon trace of the failing robocopy, so we can see exactly what the failure is.

**Comment by jrbriggs** [comment]
Closing the issue since we don't have a repro here.
