### ISSUE TITLE
Feature Request: Chocolatey Package

### ISSUE THREAD

**Issue by lavahot** [microsoft/VFSForGit#1430]
Would it be possible to introduce the distribution of the GVFS client as a chocolatey package? I don't think it would very difficult to do for anyone familiar with making chocolatey packages.

**Comment by jrbriggs** [comment]
Thanks for the idea, @lavahot . For now we're not going to publish to chocolatey. I don't think there's a broad enough need right now. We'll revisit if we find evidence to the contrary.

**Comment by brandonmcclure** [comment]
I would like to add my voice to this idea. I manage my organization's git/git lfs installs through chocolatey, and the lack of a VFS for git package is a rather large block in our adoption/testing, especially given the amazing velocity that you are releasing at!
