### ISSUE TITLE
GVFS.Service crashes when trying to set Console.InputEncoding in GitProcess()

### ISSUE THREAD

**Issue by wilbaker** [Microsoft/VFSForGit#144]
GVFS.Service crashes when trying to set Console.InputEncoding in GitProcess() (when `Console.InputEncoding.CodePage == UTF8NoBOM.CodePage` is true).

Making matters worse, GVFS.Service will not try to create a GitProcess() when starting, resulting in it crashing immediately.

**Comment by jamill** [comment]
Fixed in latest branches
