### ISSUE TITLE
Periodically log remaining hard drive space when it's getting low

### ISSUE THREAD

**Issue by wilbaker** [Microsoft/VFSForGit#146]
This will help with diagnosing user issues that were due to running out of hard drive space.

**Comment by jrbriggs** [comment]
@jeschu1 I feel like we added this logging to the heartbeat during the reliability push. Can you confirm?

/cc @wilbaker

**Comment by jeschu1** [comment]
@jrbriggs @wilbaker Indeed we did https://github.com/Microsoft/VFSForGit/pull/536

**Comment by jrbriggs** [comment]
Perfect, thank you!
