### ISSUE TITLE
"ls -l" reports 0 file size

### ISSUE THREAD

**Issue by jeschu1** [microsoft/VFSForGit#1494]
1. Clone/Mount a repository
2. cd into a directory
3. Run `ls -l` you will see many files of size 0
4. Run `ls -l` again, you will see the correct file size

It appears `ls -l` is not blocking on file size.  @pmj can you dig in here and determine the cause.  

@wilbaker / @jrbriggs for reference

**Comment by pmj** [comment]
After looking into this by tracing the `ls` syscalls using `dtruss` and their effects in ProjFS using the new `prjfs-tracectl` from #1457, my hypothesis is that `ls` first queries the size using the [`getattrlistbulk()` syscall](), which [does *not* trigger a kauth callback on each individual file queried, only the directory itself](https://github.com/apple/darwin-xnu/blob/master/bsd/vfs/vfs_attrlist.c#L3804). (`KAUTH_VNODE_LIST_DIRECTORY | KAUTH_VNODE_SEARCH`) It's then followed up by some `stat` variant, (it looks like it's primarily the undocumented `lstat64_extended()` on regular files and `fstatat64()` on subdirectories) which does cause a kauth vnode callback and hydration.

I will confirm this by writing a small tool that calls `getattrlistbulk()` to list the contents of a directory including file sizes, and see if that does indeed return 0 for unhydrated files and does not itself hydrate them.

**Comment by pmj** [comment]
Looks like I was wrong, we get a `READ_ATTRIBUTES` action callback for every file when performing a `getattrlistbulk()` on a directory, requesting name and size (data stream length), and the reported file size is correct. (post-hydration)

I'll have to dig deeper.

**Comment by pmj** [comment]
Based on the above I think this issue can be closed, what do you think, @jeschu1 and @wilbaker ?

**Comment by wilbaker** [comment]
I agree and I will close this issue.  Thanks for the in-depth analysis @pmj!
