### ISSUE TITLE
Q: Access rights and requirements

### ISSUE THREAD

**Issue by mcologne** [microsoft/VFSForGit#1501]
Hello, 

I have two questions about VFS:

1.: Is it possible to set access restrictions to an folder inside a repository? Or something similar? 
2.: Is Visual Studio Team Foundation Server 2015 supported? 

Thanks for the answer.

King regards
mcologne

**Comment by jrbriggs** [comment]
@mcologne 
1. No, this is not how Git works, and VFS for Git respects Git's security model.
2. No.
