### ISSUE TITLE
Gvfs sparse projection changes do not update open file explorer windows

### ISSUE THREAD

**Issue by judemars** [microsoft/VFSForGit#1532]
Not sure if there is a possible fix for this but I can see this being a major pain point. Here is what I did:

1. Open file explorer to the root of our repo, see all folders
2. Call gvfs sparse --set word to scope it to only word
3. File explorer still shows all folders. Also, if I try to click on one of them I get this message:

![image](https://user-images.githubusercontent.com/40219666/65926318-8ad98480-e3a9-11e9-8339-6af55f910748.png)

For office, users will not be interacting with gvfs directly, scoper will change their projection for them. I can see it being confusing if a user opens a stale file explorer window and they click on a folder and get this error message and not know why.

**Comment by wilbaker** [comment]
@kewillford to confirm, what is the state of things on disk at this point?

Did VFS4G delete the folder and it's still appearing in explorer?

**Comment by kewillford** [comment]
@wilbaker Yes, all the folders except for `word` should have been deleted/removed from the projection.  While I was trying some things, explorer did update the directories when I tried this so I must be doing something different.  I will keep trying this out and see if I can repro it.

**Comment by wilbaker** [comment]
@kewillford ok thanks! If you are able to repro I think the next step is engaging the ProjFS team.  I am not sure why Explorer would not refresh when the folders are deleted.

**Comment by kewillford** [comment]
From Christian Allred:
>The issue where Explorer doesn’t refresh when folders are removed from the projection sounds expected.  Explorer keeps an open handle to the folder it is showing.  I believe it uses directory change notifications to tell it to refresh the view.  Altering the projection doesn’t fire a change notification because it doesn’t cause anything in the open folder to be changed, not for real anyway.  Changing the projection is really more of a promise to do things differently in the future, not a change in the present.  That is, it just changes what you will show to the user the next time he tries to access something in the folder.  To get Explorer to refresh you need to change something in the real folder.  For example, you could create and then immediately delete a dummy file.  That would signal a change to Explorer, and it would enumerate and see the projection changes.

I'm leaning that we don't do anything with this because we don't know what folders the user has open in explorer so to fix this completely we would have to create and delete a file in the parent of every folder that was added or removed.  That could be a lot especially in the case of using `--disable` when I have the hosable list of folders in the sparse set.

Let me know what you think @judemars .

**Comment by judemars** [comment]
I understand that under the hood this is true "Changing the projection is really more of a promise to do things differently in the future, not a change in the present" - but I feel like this fundamentally goes against the idea of vfs for git being a true "virtual" file system. The benefit of it is that users don't need to know a lot about what is happening under the hood - so an explanation of "this didn't actually change anything" won't make sense to them without a deeper understanding of vfs for git. I see this as a big problem for office users - since our plan is to not have them interact with gvfs sparse directly, but instead have a tool that does it for them - especially because at the time they get that error message it is not clear at all that it was even vfs for git that caused the issue. Do we know what the time cost would be for creating those dummy files if we needed to? Maybe we can make this an opt-in flag that we could enable for just our users (since we are abstracting gvfs sparse away from them).

**Comment by kewillford** [comment]
The big question for me would be, should this be VFS for Git's responsibility or the tool that is doing things automagically?  @jrbriggs for his thoughts.

**Comment by jrbriggs** [comment]
My opinion is that I suspect this is a *relatively* rare case if the only affected folder is Explorer. Have we tried something like Visual Studio in folder mode? If IDEs and editors like VS Code do the Right Thing let's try shipping as-is. We can always drop the dummy files later if users hit this more frequently than I expect.
/cc @kewillford @judemars

**Comment by kewillford** [comment]
Testing in VSCode and it does refresh when folders are removed from the projection for example if I run `gvfs sparse --set word` then the view is refreshed to only show the `word` folder but if I then run `gvfs sparse --disable` to get all the folders back, I have to manually click the refresh button.

**Comment by kewillford** [comment]
Testing VS 2019 in folder mode and it is updating as expected.

**Comment by kewillford** [comment]
Testing VS 2017 works the same as VS Code.

**Comment by jrbriggs** [comment]
Ok so the gap here is when virtual folders pop into existence. What if we create/delete one dummy file at the virtualization root?

**Comment by kewillford** [comment]
That will work when we are adding/removing root folders but there could be folders N levels deep being added/removed.  For example, if I add `util/abc` and/or remove `util/cba`, the `util` folder will not get updated based on my explorer testing even if we create/delete a dummy file in the working directory root.  So we would need to create/delete one dummy file in the parent directory of each folder that was added/removed in order to cover all scenarios.  We might also have to walk up the parent folders because if `a/b/c` was added, we would need to make sure `a`, `b`, and `c` were showing up but we wouldn't know which were new folders for this projection change.

**Comment by wilbaker** [comment]
> We might also have to walk up the parent folders because if a/b/c was added, we would need to make sure a, b, and c were showing up but we wouldn't know which were new folders for this projection change

Have you tried testing this scenario?  I wonder if a change in the child folder would be enough to trigger a refresh of its parents in Explorer and VSCode.

**Comment by kewillford** [comment]
It is when folders are removed but in my testing if a folder is added that is not triggering any refresh.  Most likely this is because they are watching the folders that are in the list and if one is removed they react but they are monitoring for new folders being added.  At least that is what my testing would indicate.

**Comment by wilbaker** [comment]
Thanks for confirming @kewillford 

@cgallred, rather than creating/deleting a temp file, do you think there is an attribute we could try tweaking on directories that are disk to force a refresh (e.g. mtime), and do you think it would be a good/bad idea to do so?

**Comment by cgallred** [comment]
@wilbaker yes, updating the mtime of a directory that's had new virtual items added to it will prompt Explorer to refresh.  I don't think it's a bad idea.  It will make timestamps under the the virtualization root be out of sync with those in the backing store, which probably doesn't matter to you.

**Comment by judemars** [comment]
Just circling around to this issue - did we decide to go with @wilbaker 's suggestion?

**Comment by kewillford** [comment]
We have it on our plate to try and see if that resolves the issue and what we need to do to make sure it is efficient in changing the mtimes especially in scenarios where there are a lot of folders that need the mtime tweaked.

**Comment by judemars** [comment]
Great! Thanks

**Comment by wilbaker** [comment]
@judemars I confirmed updating the directories' last write time does trigger a refresh in Explorer.

A PR is open with the changes here: #1586
