### ISSUE TITLE
VFS4G does not merge post-command hooks that are configured per-repo

### ISSUE THREAD

**Issue by wilbaker** [microsoft/VFSForGit#1563]
**Steps to Reproduce**

1. Configure a custom post-command hook in the repo specific git config
2. Remount the repo
3. Observe: The merged `post-command.hooks` file is missing the custom command.  If the setting is configured in the global or system config VFS4G will pick it up.

**Likely Cause**

https://github.com/microsoft/VFSForGit/blob/7390eba79729141c9042b93750a108cdf4dafc2a/GVFS/GVFS.Platform.Windows/WindowsGitHooksInstaller.cs#L46

`forceOutsideEnlistment: true` results in `git config` being called outside of the repo *and* without specifying a .git directory.

As a result, `MergeHooks` is only considering `gvfs.clone.default-post-command` settings that are configured at the global and system level

**Comment by derrickstolee** [comment]
Good find! We should be able to run `git config` pointed at the `.git` directory in a way that doesn't trigger the pre- and post-command hooks, right?

**Comment by wilbaker** [comment]
> We should be able to run git config pointed at the .git directory in a way that doesn't trigger the pre- and post-command hooks, right?

I think that we probably *could* do this (e.g. I think `-c core.gvfs=false` might do it), but I'm not sure that we need to.

VFS4G is already reading the local config settings in `GVFSVerb.TrySetRequiredGitConfigSettings` [when mounting](https://github.com/microsoft/VFSForGit/blob/42763a6c1907df4894e9707e4806e9f0dceceeb3/GVFS/GVFS/CommandLine/MountVerb.cs#L267) and the fact that the hooks are called at that time has not caused a problem.

This does mean that the hooks called during that call to `git config` itself would be the pre-merged hooked, but all hooks called afterward should use the updated hooks.
