### ISSUE TITLE
Gvfs sparse --set --prune fails when top level file is edited

### ISSUE THREAD

**Issue by judemars** [microsoft/VFSForGit#1588]
Expected: File at root level of repo, when edited/added, should not effect gvfs sparse command since it is outside of the cone of concern

Behavior: When I add blah.txt at the root level, it blocks further calls to gvfs sparse

D:\mono\src>gvfs sparse --set otools --prune
Running git status...Succeeded
Updating sparse folder set...Succeeded
No folders to update in sparse set.
Finding folders to prune...Succeeded
Found 0 folders to prune.

D:\mono\src>touch blah.txt

D:\mono\src>gvfs sparse --set otools --prune
Running git status...Failed

?? blah.txt 

git status reported that you have dirty files
Either commit your changes or reset and clean

Sparse was aborted.

**Comment by wilbaker** [comment]
Duplicated by #1604
