### ISSUE TITLE
Is this actually a released product?

### ISSUE THREAD

**Issue by Korporal** [microsoft/VFSForGit#1643]
Is VFS actually a completed, released component or not? I am still unclear on whether this is going to become part of Windows or part of Visual Studip etc. Most of the info on the README is about building it but what if I am just a developer who wants to use it?

Thx

**Comment by derrickstolee** [comment]
Please see [our releases page](https://github.com/microsoft/VFSForGit/releases) for downloading the latest version. We use the "pre-release" designation mostly for workflow when sending updates in waves to the internal teams using it, but we generally recommend that you download and install the latest version on that page.

VFS for Git will never be distributed automatically as part of Windows or Visual Studio.

**Comment by Korporal** [comment]
@derrickstolee - OK this is helpful, thanks.
