### ISSUE TITLE
Harden handling of .hooks during mount and repair

### ISSUE THREAD

**Issue by jrbriggs** [Microsoft/VFSForGit#168]
If the pre-command.hooks and/or post-command.hooks files are corrupted, `gvfs mount` and `gvfs repair` both fail with a CreateProcess error when they call `git config`.

`gvfs mount` already has code to regenerate the .hooks files, but it calls `git config` before it gets to regenerating those files, so there is an ordering issue there.

Several issues to investigate here:

0. These hooks are always updated, making corruption more likely. Do we always need to update the hooks?
1. Why does a sudden reboot cause the .hooks files to get corrupted? Those files ought to be readonly. Maybe the reboot happened while mount was recreating the .hooks files? It does appear that mount always blindly recreates those files, even if they did not need to change, so that seems likely.
2. Can we rearrange the code so that we check/fix the .hooks files before we ever call a git command? That could result in a nasty refactoring problem because the constructor of GVFSEnlistment currently calls `git config`, and that happens before MountVerb is ever called.
3. Can we call `git config` with a parameter to tell it to skip calling any hooks?
4. Should we just delete the .hooks files before calling `git config`, since we're going to recreate them anyway?
5. Should `gvfs repair` also be smart enough to fix these files?

Was 970042 and 1166071

**Comment by jrbriggs** [comment]
@sanoursa brought up the good point that we should move to the robust write-and-rename pattern we use elsewhere in VFSForGit to eliminate the torn writes.

**Comment by jeschu1** [comment]
@jrbriggs It looks like this fix was addressed in [this PR](https://dev.azure.com/mseng/VSOnline/_git/GVFS/pullrequest/328163?_a=files) and released [here](https://dev.azure.com/mseng/VSOnline/_git/GVFS/pullrequest/338845?_a=overview) .  @kewillford added the write-and-rename trick so the file should always be in a good state.  The last report I see in the GVFS Dogfood was from 7/16 which would have been around the release time.  Are we sure this is still an issue?

**Comment by jrbriggs** [comment]
Thanks for the investigation. Sounds like no further action is needed on this issue.
