### ISSUE TITLE
`gvfs clone` failing to find `GVFS.Hooks.exe`

### ISSUE THREAD

**Issue by derrickstolee** [microsoft/VFSForGit#1684]
Some users are struggling with `gvfs clone` with a warning that `GVFS.Hooks.exe` is missing.

**Comment by ldennington** [comment]
For example, a user ran this command after installing VFS4G:
"C:\Program Files\GVFS\GVFS.exe" clone https://office.visualstudio.com/office/_git/Office E:\otemp

And got the following output:
Could not find GVFS.Hooks.exe

Here is the contents of his C:\Program Files\GVFS\ directory:
 Directory of C:\Program Files\GVFS

 

07/23/2020  10:16 AM    <DIR>          .
07/23/2020  10:16 AM    <DIR>          ..
11/05/2016  01:30 AM           184,832 CommandLine.dll
07/05/2016  03:26 PM            71,064 Esent.Collections.dll
07/05/2016  03:26 PM           177,664 Esent.Collections.pdb
07/05/2016  03:26 PM           413,080 Esent.Interop.dll
07/05/2016  03:26 PM         1,072,640 Esent.Interop.pdb
07/05/2016  03:26 PM           126,360 Esent.Isam.dll
07/05/2016  03:26 PM           366,080 Esent.Isam.pdb
12/18/2018  04:01 PM         1,307,648 e_sqlite3.dll
07/23/2020  10:16 AM    <DIR>          Filter
04/20/2019  11:54 AM         1,208,320 git2.dll
06/23/2020  11:23 AM           270,728 GitHooksLoader.exe
06/23/2020  11:20 AM         6,279,168 GitHooksLoader.pdb
06/23/2020  11:19 AM            67,646 GitVirtualFileSystem.ico
06/23/2020  11:20 AM           399,360 GVFS.Common.dll
06/23/2020  11:20 AM           127,432 GVFS.Common.pdb
06/23/2020  11:22 AM           165,752 GVFS.exe
06/23/2020  11:20 AM            18,401 GVFS.exe.config
06/23/2020  11:20 AM             4,608 GVFS.GVFlt.dll
06/23/2020  11:20 AM            11,776 GVFS.GVFlt.pdb
**06/23/2020  11:22 AM            68,480 GVFS.Hooks.exe**
06/23/2020  11:19 AM               187 GVFS.Hooks.exe.config
06/23/2020  11:20 AM           114,176 GVFS.Hooks.pdb
06/23/2020  11:22 AM            36,744 GVFS.Mount.exe
06/23/2020  11:20 AM            18,072 GVFS.Mount.exe.config
06/23/2020  11:20 AM            40,448 GVFS.Mount.pdb
06/23/2020  11:20 AM           249,344 GVFS.pdb
06/23/2020  11:20 AM           104,448 GVFS.Platform.Windows.dll
06/23/2020  11:20 AM           179,712 GVFS.Platform.Windows.pdb
06/23/2020  11:22 AM           149,408 GVFS.PostIndexChangedHook.exe
06/23/2020  11:20 AM         4,935,680 GVFS.PostIndexChangedHook.pdb
06/23/2020  11:21 AM           156,568 GVFS.ReadObjectHook.exe
06/23/2020  11:20 AM         5,017,600 GVFS.ReadObjectHook.pdb
06/23/2020  11:22 AM            47,496 GVFS.Service.exe
06/23/2020  11:20 AM            18,072 GVFS.Service.exe.config
06/23/2020  11:20 AM            73,216 GVFS.Service.pdb
06/23/2020  11:22 AM            27,520 GVFS.Service.UI.exe
06/23/2020  11:20 AM            18,072 GVFS.Service.UI.exe.config
06/23/2020  11:20 AM            42,496 GVFS.Service.UI.pdb
06/23/2020  11:22 AM            22,920 GVFS.Upgrader.exe
06/23/2020  11:21 AM            18,401 GVFS.Upgrader.exe.config
06/23/2020  11:21 AM             3,420 GVFS.Upgrader.pdb
06/23/2020  11:22 AM           147,368 GVFS.VirtualFileSystemHook.exe
06/23/2020  11:20 AM         4,927,488 GVFS.VirtualFileSystemHook.pdb
06/23/2020  11:20 AM            92,160 GVFS.Virtualization.dll
06/23/2020  11:20 AM            33,208 GVFS.Virtualization.pdb
03/22/2019  05:06 AM           135,032 Microsoft.Data.Sqlite.dll
05/30/2018  08:46 PM           675,112 msvcp140.dll
05/30/2018  08:46 PM            32,048 msvcp140_1.dll
05/30/2018  08:46 PM           195,888 msvcp140_2.dll
06/04/2020  01:57 PM            98,616 netstandard.dll
03/24/2018  05:44 PM           662,528 Newtonsoft.Json.dll
11/30/2018  02:38 AM           477,936 NuGet.Commands.dll
11/30/2018  02:38 AM            98,544 NuGet.Common.dll
11/30/2018  02:38 AM           138,480 NuGet.Configuration.dll
11/30/2018  02:38 AM           108,808 NuGet.Frameworks.dll
11/30/2018  02:38 AM            52,464 NuGet.Packaging.Core.dll
11/30/2018  02:38 AM           581,872 NuGet.Packaging.dll
11/30/2018  02:38 AM           672,496 NuGet.Protocol.dll
11/30/2018  02:38 AM            52,464 NuGet.Versioning.dll
07/23/2020  10:16 AM                 0 OnDiskVersion16CapableInstallation.dat
07/23/2020  10:16 AM    <DIR>          ProgramData
06/05/2019  09:57 PM           339,312 ProjectedFSLib.Managed.dll
07/23/2020  10:16 AM    <DIR>          ProjFS
12/18/2018  04:00 PM             5,120 SQLitePCLRaw.batteries_green.dll
12/18/2018  04:00 PM             5,120 SQLitePCLRaw.batteries_v2.dll
12/18/2018  04:00 PM            38,400 SQLitePCLRaw.core.dll
12/18/2018  04:00 PM            39,936 SQLitePCLRaw.provider.e_sqlite3.dll
06/04/2020  01:57 PM           110,944 System.IO.Compression.dll
06/04/2020  01:57 PM           198,472 System.Net.Http.dll
06/04/2020  01:57 PM            29,360 System.Runtime.dll
06/04/2020  01:57 PM            79,176 System.ValueTuple.dll
07/23/2020  10:16 AM            31,953 unins000.dat
07/23/2020  10:16 AM         1,265,361 unins000.exe
05/30/2018  08:46 PM            87,864 vcruntime140.dll

Also, his environment variable dump for reference:
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\sadixon\AppData\Roaming
BBDIFF=E:\Ogit1\src\otools\bin\sdvdiff.exe --sd
ChocolateyInstall=C:\ProgramData\chocolatey
ChocolateyLastPathUpdate=132228088143369283
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=SAMDEV1
ComSpec=C:\WINDOWS\system32\cmd.exe
COPYCMD=/Y
CORECLR_ENABLE_PROFILING=0
CORECLR_PROFILER={8360CB03-C250-460e-A4B3-EBF549935622}
COR_ENABLE_PROFILING=0
COR_PROFILER={8360CB03-C250-460e-A4B3-EBF549935622}
Coverage=C:\ProgramData\Coverage
DriverData=C:\Windows\System32\Drivers\DriverData
GIT_TR2_CONFIG_PARAMS=scalar.*,gvfs.*,remote.origin.url,user.*
GIT_TR2_EVENT=\\.\pipe\git-c780ac06-135a-4e9e-ab6c-d41e2d265baa
GIT_TRACE2_CONFIG_PARAMS=scalar.*,gvfs.*,remote.origin.url,user.*
GIT_TRACE2_EVENT=\\.\pipe\git-c780ac06-135a-4e9e-ab6c-d41e2d265baa
HOMEDRIVE=C:
HOMEPATH=\Users\sadixon
IntelliJ IDEA Community Edition=C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.1\bin;
JAVA_HOME=C:\Program Files\Android\Jdk\microsoft_dist_openjdk_1.8.0.25
JJPACK_DIFF=E:\Ogit1\src\otools\bin\sdvdiff.exe
LOCALAPPDATA=C:\Users\sadixon\AppData\Local
LOGONSERVER=\\CY1-RED-DC-45
MORE=/E
NugetMachineInstallRoot=E:\NugetCache
NUMBER_OF_PROCESSORS=16
OneDrive=C:\Users\sadixon\OneDrive
OS=Windows_NT
OSETUPPATH=\\offdepot1\osetup\git\osetup.exe
Path=C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Python27\;C:\Python27\Scripts;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Gumshoe\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Git\cmd;C:\Program Files\Scalar;C:\Program Files\dotnet\;C:\Users\sadixon\AppData\Local\Microsoft\WindowsApps;E:\Ogit1\Build\MetaBuild\NugetGenerated\dotnetCliHome\.dotnet\tools;C:\Users\sadixon\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\sadixon\.dotnet\tools;E:\UserRepos\sadixon\bin;E:\O0\Build\MetaBuild\NugetGenerated\dotnetCliHome\.dotnet\tools;C:\Users\sadixon\AppData\Roaming\npm;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.1\bin;E:\UserRepos\jacobl\bin;E:\Ogit3\Office\Build\MetaBuild\NugetGenerated\dotnetCliHome\.dotnet\tools;C:\Users\sadixon\AppData\Local\Microsoft\WindowsApps;C:\Users\sadixon\.dotnet\tools
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 85 Stepping 4, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=5504
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files\Intel\Wired Networking\
PUBLIC=C:\Users\Public
SDFDIFF=E:\Ogit1\src\otools\bin\sdvdiff.exe --sd -LO
SDPWDIFF=E:\Ogit1\src\otools\bin\sdvdiff.exe
SDVCDIFF=E:\Ogit1\src\otools\bin\sdvdiff.exe --sd -LD
SDVDIFF=E:\Ogit1\src\otools\bin\sdvdiff.exe --sd
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\sadixon\AppData\Local\Temp
TMP=C:\Users\sadixon\AppData\Local\Temp
USERDNSDOMAIN=REDMOND.CORP.MICROSOFT.COM
USERDOMAIN=REDMOND
USERDOMAIN_ROAMINGPROFILE=REDMOND
USERNAME=sadixon
USERPROFILE=C:\Users\sadixon
USERROOT=E:\UserRepos
VCINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
VS2019OCHECKCONFIG=5
windir=C:\WINDOWS
_NT_SOURCE_PATH=srv*
_NT_SYMBOL_PATH=cache*C:\symbols;srv*http://offsym/symbols;srv*https://symweb
_NT_SYMCACHE_PATH=C:\symcache*\\twcperfstore\symcache*http://symcache

**Comment by derrickstolee** [comment]
closing unless this pops up again.
