### ISSUE TITLE
AzureDevops 2019, git push error. Correct with 'standard' git

### ISSUE THREAD

**Issue by lbellego** [microsoft/VFSForGit#1687]
Git push error:
fatal: bad object ea0a2651bfd6f2ac5c824ff6be8db341c3b43d5a
error: remote unpack failed: error TF401030: The Git pack header is invalid.
remote: TF401030: The Git pack header is invalid.
fatal: the remote end hung up unexpectedly
fatal: the remote end hung up unexpectedly

I tried 2.28, 2.27, 2.26, 2.22....same error (with gvs). It's not a gvs repo, normal Git.
I install the last Git official release (without gvfs) and I can push !!

**Comment by derrickstolee** [comment]
If you are using VFS for Git, then you need to be using the version of Git that is paired with that release. Normal Git for Windows does not know how to handle missing objects or how to communicate with VFS for Git to download.

![image](https://user-images.githubusercontent.com/570044/89185625-8a30f200-d568-11ea-805c-b9e5fe77b43a.png)

This image shows where you can find the Git download associated with your VFS for Git release.
