### ISSUE TITLE
Can't see the src directory through samba

### ISSUE THREAD

**Issue by NevermoreDong** [microsoft/VFSForGit#1688]
In the windows environment, map the linux directory through samba。
Can't see the code in the src directory。
Because the file system of the directory is /dev/fuse ？

/dev/fuse            787G  2.9G  744G   1% /home/share/gvfs-test/gvfstest.git/src

**Comment by derrickstolee** [comment]
Unfortunately, I don't believe this is a scenario we plan to support.
