### ISSUE TITLE
Check for and recover from altitude collisions with gvflt

### ISSUE THREAD

**Issue by jrbriggs** [Microsoft/VFSForGit#169]
GVFS.Service could check for the Win32Exception “An instance already exists at this altitude on the volume specified” specifically when it’s trying to start prjflt.  If this exception does occur it could optimistically check for (and remove) gvflt and then try starting prjflt again.

**Comment by sanoursa** [comment]
Closing this out since we haven't seen any reports in a long while and it's unlikely anyone has the old gvflt driver installed at this point.
