### ISSUE TITLE
Why is evrything treating as "binary" a requirement?

### ISSUE THREAD

**Issue by gabyx** [microsoft/VFSForGit#1690]
I am wondering about the fact that `* -text` in `.gitattributes` is a requirement for GVFS? This means everything is treated as "binary".
Why is that, and isn't that conflicting with merge conflict behavior and diffing?  Why does that make sense? Could you maybe clear that point in the Documentation?

**Comment by derrickstolee** [comment]
By using `* -text` and not `* binary`, the merge behavior is preserved.

This is used to guarantee that no filters are used when writing files to disk. The most common such filter is `auto.crlf` which converts LF newlines (`\n`) to CRLF newlines (`\r\n`). These conversions are (a) slow and (b) make the file-size information unpredictable, violating the projection that VFS for Git provides.

**Comment by gabyx** [comment]
Thanks, so that is also useful when we want to make sure in a repo that end of line normalization **never** happens (no matter what users set in their `core.autocrlf`:

we can simply just add:
```shell
* -text
```
