### ISSUE TITLE
Long branch names stalling ingestion

### ISSUE THREAD

**Issue by stephanams** [microsoft/VFSForGit#1691]
Recently we encountered an issue during the ingestion where teams where using auto-generated branch names like `some_really_long_branch_name_that_was_autogenerated_and_exceeded_the_256_character_path_name_limit_on_windows_12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890`. This led to the ingestion being stalled for that repository. The error found in the ingestion log was

```
{"Progress":"error: cannot lock ref 'refs/remotes/origin/user/username/some_really_long_branch_name_that_was_autogenerated_and_exceeded_the_256_character_path_name_limit_on_windows_12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890': Unable to create 'D:/GvfsCache/Proxy/gvfs/69c86f57d071450dbeb9ed27a2e8d0a9/./refs/remotes/origin/user/username/some_really_long_branch_name_that_was_autogenerated_and_exceeded_the_256_character_path_name_limit_on_windows_12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890.lock': Invalid argument","IsPublic":false,"TimeStamp":"2020-09-16T17:06:23.9490697+00:00"}

{"Progress":"error: cannot lock ref 'refs/remotes/origin/user/username/some_really_long_branch_name_that_was_autogenerated_and_exceeded_the_256_character_path_name_limit_on_windows_1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789001234567890012345678900123456789001234567890012345': Unable to create 'D:/GvfsCache/Proxy/gvfs/69c86f57d071450dbeb9ed27a2e8d0a9/./refs/remotes/origin/user/username/some_really_long_branch_name_that_was_autogenerated_and_exceeded_the_256_character_path_name_limit_on_windows_1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789001234567890012345678900123456789001234567890012345.lock': Invalid argument","IsPublic":false,"TimeStamp":"2020-09-16T17:06:24.0896816+00:00"}

```

In essence Git failed to create the lock file, since file path `D:/GvfsCache/Proxy/gvfs/69c86f57d071450dbeb9ed27a2e8d0a9/./refs/remotes/origin/user/username/some_really_long_branch_name_that_was_autogenerated_and_exceeded_the_256_character_path_name_limit_on_windows_1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789001234567890012345678900123456789001234567890012345.lock` exceeded the max. path length of the underlying operating system.

You can find more details in Microsoft IcM ticket 205447797.

**Comment by dscho** [comment]
The path limit is actually smaller than 256, in practice more like 240.

You could try running with `core.longpaths = true`, but IIRC there are some performance implications in that.

**Comment by derrickstolee** [comment]
Yes, this is a core Git issue in that it uses refs as file paths to store the values. Long paths will run into issues at the platform level, and some are at the Git level (to prevent accidentally causing problems with other users who have small platform limits).

There is nothing to do in VFS for Git to fix this. Instead, I recommend:

1. Don't do that! There is probably very little reason to need such long paths.
2. Use Git features like `core.longPaths = true`. This is only an option in Git for Windows, so [the documentation for the option](https://github.com/git-for-windows/git/blob/5300e52e185605f22d1a205f072a813d6281a1a3/Documentation/config/core.txt#L573-L578) is not on git-scm.com.
