### ISSUE TITLE
Certificate expired for https://vfsforgit.org/

### ISSUE THREAD

**Issue by sluongng** [microsoft/VFSForGit#1705]
It seems like the certificate for HTTPS has expired 

```
Expired: Thursday, November 26, 2020 at 15:54:14 Central European Standard Time

```

Could somebody on MSFT side replace this?

**Comment by derrickstolee** [comment]
I think we looked into this recently, but no one really owns this web page anymore. Thoughts, @vtbassmatt?

**Comment by vtbassmatt** [comment]
@ethomson took care of it I think.

**Comment by sluongng** [comment]
From my side

```
> echo | openssl s_client -servername vfsforgit.org -connect vfsforgit.org:443 | openssl x509 -noout -dates
depth=2 C = IE, O = Baltimore, OU = CyberTrust, CN = Baltimore CyberTrust Root
verify return:1
depth=1 C = US, ST = Washington, L = Redmond, O = Microsoft Corporation, OU = Microsoft IT, CN = Microsoft IT TLS CA 5
verify return:1
depth=0 CN = vfsforgit.org
verify error:num=10:certificate has expired
notAfter=Nov 26 14:54:14 2020 GMT
verify return:1
depth=0 CN = vfsforgit.org
notAfter=Nov 26 14:54:14 2020 GMT
verify return:1
DONE
notBefore=Nov 26 14:54:14 2018 GMT
notAfter=Nov 26 14:54:14 2020 GMT
```

**Comment by vtbassmatt** [comment]
Sorry, what I mean was he took care of it last time. Since this is no longer his area of ownership, I'm having the domains and cert privileges transferred to myself. It may take a bit of time - we have to work through multiple systems. Thanks for reporting this!

**Comment by vtbassmatt** [comment]
This issue isn't forgotten. I need manager approval to issue the certificate, and the interface to let my manager do so is giving us a lot of trouble ☹️

**Comment by vtbassmatt** [comment]
Our site team was finally able to break the logjam on this. So sorry it took this long to fix 😞
