### ISSUE TITLE
Broken links for articles about the details of VFS for Git

### ISSUE THREAD

**Issue by joshtriplett** [microsoft/VFSForGit#1724]
The links for "Git at Scale", "Technical Scale Challenges", and "VFS for Git Design History" all lead to 404 pages now. I'd love to read the original articles; is there a new URL available that the homepage could link to?

**Comment by derrickstolee** [comment]
You're meaning the links on https://vfsforgit.org/ which _are_ broken, but are not maintained by this repository.

Perhaps @vtbassmatt knows how to fix this, but otherwise we might close this as "won't fix" (because we don't have those files anymore).

**Comment by vtbassmatt** [comment]
Those topics have new URLs on the Microsoft docs site. I'll get this fixed.

**Comment by vtbassmatt** [comment]
Fix has been deployed.

**Comment by joshtriplett** [comment]
Thank you!
