### ISSUE TITLE
Race condition in BatchObjectDownloadStage

### ISSUE THREAD

**Issue by tyrielv** [microsoft/VFSForGit#1743]
I hit a situation when prefetching with "--files *" when almost all the blobs were already present. The logs showed that 3 blobs were missing, but that no download requests were made. The missing blobs were not actually downloaded (which wouldn't be a problem working with git through commandline or file system, but I was trying to use Libgit2 to build a tree using the blobs and it failed because they were missing). Running "gvfs prefetch --files *" again claimed that all blobs were prefetched so there was nothing to download, but they were still missing. Running "gvfs prefetch --files" and providing the actual files needed caused them to be prefetched.

I suspect that there is a race condition in BatchObjectDownloadStage between 
[L222 ](https://github.com/microsoft/VFSForGit/blob/a61e4dc82582d38efde0fd4c450efb5d1abe722a/GVFS/GVFS.Common/Prefetch/Pipeline/BatchObjectDownloadStage.cs#L222) and [L227](https://github.com/microsoft/VFSForGit/blob/a61e4dc82582d38efde0fd4c450efb5d1abe722a/GVFS/GVFS.Common/Prefetch/Pipeline/BatchObjectDownloadStage.cs#L227). It seems possible for the missingBlobs collection to finish adding in between those two lines, in which case any blobs that were added during that time would not be downloaded.

**Comment by derrickstolee** [comment]
Maybe there is something about that `this.missingBlobs.IsAddingCompleted`, since otherwise it would loop 4000 times (waiting 100ms each time) before quitting if no blobs are added to the list.

If you use the `--hydrate` option on the `gvfs prefetch --files` command, does that populate the files?

**Comment by tyrielv** [comment]
Now that you mention it, the 4000x loop seems like a more likely culprit than that tiny race condition, especially since I'm able to repro it on a fresh clone - it took nearly an hour (much longer than 400 seconds) for gvfs to finish determining that only 3 blobs needed to be downloaded.
