### ISSUE TITLE
Consider upgrading LibGit2Sharp.NativeBinaries as they are over 3 years old

### ISSUE THREAD

**Issue by GabeDeBacker** [microsoft/VFSForGit#1770]
Recently we've seen a number of crashes in Windows OS developer telemetry originating from GVFS related to the native binaries packaged with GVFS from the LibGit2Sharp.NativeBinaries nuget package.

Specifically, we are seeing these two issues:
https://github.com/libgit2/libgit2/issues/5207

https://github.com/libgit2/libgit2/issues/5154

After cloning VFSForGit repository, I discovered the package being used for LibGit2 was over three years old.

    <PackageReference Include="LibGit2Sharp.NativeBinaries" Version="2.0.278" />

https://www.nuget.org/packages/LibGit2Sharp.NativeBinaries/2.0.278

Which was released on 4/20/2019.

The fix for the above issues addressed:
https://github.com/libgit2/libgit2/pull/5314

On 10/30/2019.

The Nuget feed for VitForGVFS
    <add key="Dependencies" value="https://pkgs.dev.azure.com/gvfs/ci/_packaging/Dependencies/nuget/v3/index.json" />

Doesn't show the package available for upgrade (I guess the feed may be locked?) so that would need to be addressed as well.

Can we get some assistance on this?

Thanks!

**Comment by dscho** [comment]
Implicitly addressed via https://github.com/microsoft/VFSForGit/pull/1815.
