### ISSUE TITLE
Is there any way to get Xcode's source control to support vfs git?

### ISSUE THREAD

**Issue by miku1958** [microsoft/VFSForGit#1776]
I tried vfs git with our mac project and found that Xcode's own git doesn't work with vfs git, is there any way to get Xcode's source control to support vfs git?

Thanks!

**Comment by derrickstolee** [comment]
There are two problems:

1. VFS for Git does not work on macOS. An implementation was attempted, but it was shut down by changes to macOS that prevented our way of working with it. Instead, macOS users are encouraged to use Scalar which is packaged with [the `microsoft/git` fork](https://github.com/microsoft/git).
2. XCode relies on a version of libgit2 compiled into its code, and not on Git commands. If it ran Git commands on the installed version of Git, then the custom code in microsoft/git would be used to handle these custom repositories.

**Comment by miku1958** [comment]
Got it, thanks!
