### ISSUE TITLE
Is the licensing problematic?

### ISSUE THREAD

**Issue by trafalmuffti** [microsoft/VFSForGit#1785]
VFSForGit is MIT licensed. Git itself is GPL licensed, made by famous GPL software writer, Linus Torvalds. There seems to be no way this could be using GPL licensed software if VFSForGit wasn't GPL licensed.

**Comment by derrickstolee** [comment]
The Git code is not included in this repository. The sibling repository `microsoft/git` is a fork of `git/git` and is available via the same license as Git.

**Comment by trafalmuffti** [comment]
Thanks, I didn't realize it worked that way. All the power to you, certainly seems like a great FS.

Apologies for whatever this question may have cost you folks.
