### ISSUE TITLE
Where does VFS For Git Mount The Repos

### ISSUE THREAD

**Issue by jonathanchapmanmoore** [microsoft/VFSForGit#1788]
I installed VFS for Git and where does in mount the Repos

![Untitled14 (8)](https://user-images.githubusercontent.com/8218836/188249718-80d1ab57-c987-409d-beee-d9ac385da768.png)

**Comment by derrickstolee** [comment]
It mounts the repos that you previously had mounted before upgrading. If this is your first install, this step does nothing (but it goes and checks to see if there is an existing list of repos, first).

**Comment by jonathanchapmanmoore** [comment]
Thank You,

But at what location on the NTFS File System Running Windows 10 LTSC 1809.

**Comment by derrickstolee** [comment]
The location is wherever you created the clones via `gvfs clone`.
