### ISSUE TITLE
TortoiseGit error: index.lock

### ISSUE THREAD

**Issue by lilhoser** [microsoft/VFSForGit#1824]
I'm unable to use TortoiseGit with gvfs:

![Image](https://github.com/user-attachments/assets/0d315d94-6e80-430b-8c56-ee54dbe79ec6)

**Comment by derrickstolee** [comment]
Third-party tools that modify your `.git/` folder are incompatible with VFS for Git. Only tools using the version of Git installed on the `PATH` will be compatible.

This signal is a sign that TortoiseGit is directly manipulating the index file, which would disrupt the virtualization layer. The `GVFS.Mount` process is holding a handle on the `.git/index` file to prevent this exact scenario.
