### ISSUE TITLE
NamedPipeServerStream.EndWaitForConnection() throws System.Net.Sockets.SocketException, which terminates the whole process

### ISSUE THREAD

**Issue by turbonaitis** [Microsoft/VFSForGit#235]
On Mac, during GVFS clone command, a `NamedPipeServer` is started and then disposed. Then `OnNewConnection` method is invoked and it tries to invoke `pipe.EndWaitForConnection(ar);`, which  throws `System.Net.Sockets.SocketException`, which is currently unhandled and reaches generic `LogErrorAndExit` path, which terminates the whole process, before it has completed prefetch or started the mount process. It seems on Windows this might behave differently and throw `ObjectDisposedException`, which is handled appropriately.

**Comment by sanoursa** [comment]
Fixed in #244
