### ISSUE TITLE
Mac: ReadFilesJob references kernel32

### ISSUE THREAD

**Issue by turbonaitis** [Microsoft/VFSForGit#243]
ReadFilesJob references kernel32.dll in attempt to do native file open/read, which results in an exception being thrown during `gvfs prefetch --files *.txt --hydrate <enlistment>`

**Comment by sanoursa** [comment]
This is still a general issue because we have not yet scrubbed all uses of kernel32. Good to keep track of this instance though.

**Comment by turbonaitis** [comment]
I guess these particular uses should go to `IPlatformFileSystem` ? I may create a PR for this next week, to unblock one of the scenarios we're trying to go through.

**Comment by sanoursa** [comment]
Yes, exactly. If I recall correctly, the only reason we're calling kernel32 functions here is that the .NET APIs always read a full page even if you request a single byte, so calling `ReadFile` directly was a bit more efficient. So as a short-term hack to test your scenario, you could just drop the kernel32 code and use `FileStream`, taking care to open for read access only (opening for write will immediately convert the file from placeholder to full, even if you never write to it). If you want to go for the proper fix, then yes I would add a method called `ReadOneByte` to `IPlatformFileSystem`.
