### ISSUE TITLE
Cannot clone GVFS repo, gvfs command not found and git reports it does not support GVFS

### ISSUE THREAD

**Issue by deathly809** [Microsoft/VFSForGit#282]
I am on Windows 10 Profession and I cannot clone a REPO from VSO.  I just installed the latest Git version under releases and removed all previous Git versions.

When I follow the example in the README.md I get this,
```bash
$ gvfs clone https://microsoft.visualstudio.com/...
bash: gvfs: command not found
```

When I do git clone,
```
$ git clone https://microsoft.visualstudio.com/...
Cloning into 'repo_name'...
remote: This repository requires GVFS. Ensure the version of git you are using supports GVFS.
fatal: protocol error: bad pack header
```

**Comment by wilbaker** [comment]
@deathly809, are you running these commands in git-bash or in the Windows Subsystem for Linux?

Currently VFS for Git cannot be used in the Linux Subsystem.  If your using git-bash it could an issue with your path.  To help narrow things down can you try running 'gvfs clone` in cmd.exe and see it it works there?

**Comment by deathly809** [comment]
Handled this over Skype.

**Comment by wilbaker** [comment]
> Handled this over Skype.

For anyone else that hits this the underlying issue was that the VFS for Git installer had not been run.
