### ISSUE TITLE
Mac: Add support for projecting symlinks

### ISSUE THREAD

**Issue by sanoursa** [Microsoft/VFSForGit#285]
Right now VFS for Git does not understand that some entries in the git index represent symlinks, so they are not projected correctly. And on Mac, the issue is made even worse because symlinks have a mode of 0, which makes the file totally inaccessible to any user except for root.

**Comment by wilbaker** [comment]
I split the original issue into two parts.  This issue is for VFS for Git projecting symbolic links, and #320 has been created to update VFS for Git to detect newly created symbolic links.
