### ISSUE TITLE
`gvfs clone` may fail due to prefetch packfile "gaps"

### ISSUE THREAD

**Issue by derrickstolee** [Microsoft/VFSForGit#306]
The prefetch packfiles use timestamps to signal "this is what the cache server knew about at this time". When a client prefetches, they contact _a_ cache server with their latest timestamp and the server responds with a list of packfiles. As we call different cache servers, we can get into a state where there are "gaps": some commits and trees never exist in a prefetch pack.

In a normal enlistment, these gaps can be refilled on-demand. However, at clone time we may be directed to an existing shared object cache, see that the cache has the commit and root tree that we expect, but be missing a tree that is reachable from that root tree. As we attempt to run a `git checkout`, we will fail to find that object and we don't have the read-object hook available.

This is a very odd data shape that has always been possible, but it is more likely to be hit now that we have background prefetch (we are more likely to satisfy `CommitAndRootTreeExists()` for the latest ref).

One fix is to run `git rev-list --objects <root-tree-hash>` instead of just checking if the objects exist. If that command succeeds, then we can continue without downloading the initial packfile. This will take less time than the `git checkout` step, so may be reasonable.

Another fix is to always download that initial packfile. This is likely not the best solution because we rarely _need_ that data a second time, and we would be slowing down clones that are usually "trivial".

**Comment by derrickstolee** [comment]
@sanoursa The implementation of TryDownloadCommit() doesn't do anything if you have the commit and root tree, as I described: https://github.com/Microsoft/VFSForGit/blob/0cf25d483f5c270d4490a9d9c75807babcafa594/GVFS/GVFS/CommandLine/GVFSVerb.cs#L406

**Comment by sanoursa** [comment]
My point is, the issue is not with prefetch. Prefetch contains full trees, so background prefetch is not at fault here. The root cause is that an existing repo could touch just the root tree object, not download the full set of trees, and then a subsequent clone attempt will fail in this manner.
