### ISSUE TITLE
Mac: Kernel panic when touching FUSE mount

### ISSUE THREAD

**Issue by hemancuso** [Microsoft/VFSForGit#340]
Using the latest code from Github and building using XCode 10, changing no settings other than signing certificate, I can consistently panic my system [10.13] by loading PrjFSKext and then browsing to a FUSE volume (Google Drive File Stream). I have not been able to get a symbolic backtrace unfortunately. It does panic instantly so it should be easy to replicate.

Thu Oct  4 14:12:11 2018

*** Panic Report ***
panic(cpu 6 caller 0xffffff800c188c2d): Kernel trap at 0xffffff800c2cab24, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x0000000000000008, CR3: 0x000000041d314015, CR4: 0x00000000003627e0
RAX: 0x0000000000000000, RBX: 0x0000000000000000, RCX: 0x0000000003000000, RDX: 0xffffff803c67f5a0
RSP: 0xffffff91fdf435b0, RBP: 0xffffff91fdf435b0, RSI: 0x0000000000000002, RDI: 0x0000000000000000
R8:  0x0000000000000073, R9:  0x0000000000000003, R10: 0xffffff8034721a40, R11: 0x0000000000000000
R12: 0xffffff803c812c18, R13: 0x0000000000000002, R14: 0xffffff91fdf43728, R15: 0xffffff803273a000
RFL: 0x0000000000010246, RIP: 0xffffff800c2cab24, CS:  0x0000000000000008, SS:  0x0000000000000000
Fault CR2: 0x0000000000000008, Error code: 0x0000000000000000, Fault CPU: 0x6, PL: 0, VF: 0

Backtrace (CPU 6), Frame : Return Address
0xffffff91fdf43060 : 0xffffff800c06e166 
0xffffff91fdf430b0 : 0xffffff800c196714 
0xffffff91fdf430f0 : 0xffffff800c188a00 
0xffffff91fdf43170 : 0xffffff800c020180 
0xffffff91fdf43190 : 0xffffff800c06dbdc 
0xffffff91fdf432c0 : 0xffffff800c06d99c 
0xffffff91fdf43320 : 0xffffff800c188c2d 
0xffffff91fdf434a0 : 0xffffff800c020180 
0xffffff91fdf434c0 : 0xffffff800c2cab24 
0xffffff91fdf435b0 : 0xffffff7f90612d80 
0xffffff91fdf43670 : 0xffffff7f906069b6 
0xffffff91fdf436a0 : 0xffffff800c2cb6a3 
0xffffff91fdf43710 : 0xffffff7f9061e1d7 
0xffffff91fdf438e0 : 0xffffff7f9061c276 
0xffffff91fdf43d50 : 0xffffff7f9061c1f8 
0xffffff91fdf43d80 : 0xffffff7f9061e152 
0xffffff91fdf43db0 : 0xffffff7f9061dafb 
0xffffff91fdf43e40 : 0xffffff800c4e9553 
0xffffff91fdf43ea0 : 0xffffff800c4f45f3 
0xffffff91fdf43f00 : 0xffffff800c4f89b4 
0xffffff91fdf43f40 : 0xffffff800c604418 
0xffffff91fdf43fa0 : 0xffffff800c020966 
      Kernel Extensions in backtrace:
         com.google.dfsfuse.filesystems.dfsfuse(3.7.4)[42D94C7E-73CB-3DCB-9C2A-FFDB5DFD8BCB]@0xffffff7f90606000->0xffffff7f9061afff
         io.gvfs.PrjFSKext(1.0)[F9BF6177-84C0-38A4-9ADE-C35FC4ECF08E]@0xffffff7f9061b000->0xffffff7f9064afff

BSD process name corresponding to current thread: mds_stores

Mac OS version:
17E199

Kernel version:
Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64
Kernel UUID: 1B55340B-0B14-3026-8A47-1E139DB63DA3
Kernel slide:     0x000000000be00000
Kernel text base: 0xffffff800c000000
__HIB  text base: 0xffffff800bf00000
System model name: MacBookPro13,3 (Mac-A5C67F76ED83108C)

**Comment by sanoursa** [comment]
Thanks for the bug report. It seems that one of the checks to decide if a kauth event is for a vnode we care about is making assumptions and FUSE (or this particular FUSE implementation) is breaking them. We will dig into it, though if you have the time, I went ahead and published my notes for resolving a backtrace here: https://github.com/Microsoft/VFSForGit/wiki/Resolving-a-kernel-backtrace

**Comment by hemancuso** [comment]
Thanks, it would've taken me a while to piece that command together.
For the above panic, using this command

> atos -o ~/work/BuildOutput/ProjFS.Mac/Native/Release/PrjFSKext.kext/Contents/MacOS/PrjFSKext -l 0xffffff7f9061b000 0xffffff7f9061e1d7 0xffffff7f9061c276 0xffffff7f9061c1f8 0xffffff7f9061e152 0xffffff7f9061dafb


```
Vnode_GetFsidAndInode(vnode*, vfs_context*) (in PrjFSKext) (VnodeUtilities.cpp:17)
VirtualizationRoots_LookupVnode(vnode*, vfs_context*) (in PrjFSKext) (VirtualizationRoots.cpp:89)
VirtualizationRoots_FindForVnode(vnode*) (in PrjFSKext) (VirtualizationRoots.cpp:68)
ShouldHandleFileOpEvent(vfs_context*, vnode*, int, VirtualizationRoot**, int*) (in PrjFSKext) (KauthHandler.cpp:640)
HandleFileOpOperation(ucred*, void*, int, unsigned long, unsigned long, unsigned long, unsigned long) (in PrjFSKext) (KauthHandler.cpp:471)
```

**Comment by pmj** [comment]
I don't think it's returning null. That line is fairly deep in the stack (more than 10 frames in), and both `vfs_statfs()` and `vnode_mount()` are leaf functions so can never be in the middle of a stack trace like that. So I assume `0xffffff7f9061e1d7 (VnodeUtilities.cpp:17)` must be the return pointer from `vnode_getattr()` and it's that that's panicking deep in FUSE. I'm going to download the 17E199 KDK and try to symbolicate the core kernel functions in that trace tomorrow and confirm the hypothesis.

If it turns out to be correct, I won't be able to work out *why* it's panicking without taking a deep dive on the FUSE kext, but I shouldn't have to fully debug it anyway: as we only support HFS+ and APFS in VFS for Git, we shouldn't be trying to get file attributes on a FUSE file system in the first place. So there's evidently some code path where we're not checking whether the file system is of interest to us, and we're calling `vnode_getattr()` on a file system that we shouldn't be touching. *That* I should be able to fix.

I'll try to get some more information in the next days.

**Comment by hemancuso** [comment]
Thanks for the tip regarding boot args, will do. FWIW even if you don't manually touch FUSE, the MDS process eventually does and takes your system down. Filtering on filesystem type, as you suggest, seems like a reasonable way to approach this.

**Comment by pmj** [comment]
I've now got a more complete call stack using the KDK:

```
handle_debugger_trap (in kernel) (debug.c:854)
kdp_i386_trap (in kernel) (cpu_data.h:534)
kernel_trap (in kernel) (trap.c:769)
trap_from_kernel (in kernel) + 38
panic_trap_to_debugger (in kernel) (cpu_data.h:400)
panic (in kernel) (debug.c:0)
kernel_trap (in kernel) (trap.c:826)
trap_from_kernel (in kernel) + 38
vfs_context_ucred (in kernel) (kpi_vfs.c:1369)
0xffffff7f90612d80
0xffffff7f906069b6
vnode_getattr (in kernel) (kpi_vfs.c:3338)
Vnode_GetFsidAndInode(vnode*, vfs_context*) (in PrjFSKext) (VnodeUtilities.cpp:17)
VirtualizationRoots_LookupVnode(vnode*, vfs_context*) (in PrjFSKext) (VirtualizationRoots.cpp:89)
VirtualizationRoots_FindForVnode(vnode*) (in PrjFSKext) (VirtualizationRoots.cpp:68)
ShouldHandleFileOpEvent(vfs_context*, vnode*, int, VirtualizationRoot**, int*) (in PrjFSKext) (KauthHandler.cpp:640)
HandleFileOpOperation(ucred*, void*, int, unsigned long, unsigned long, unsigned long, unsigned long) (in PrjFSKext) (KauthHandler.cpp:471)
kauth_authorize_fileop (in kernel) (kern_authorization.c:411)
close_internal_locked (in kernel) (kern_descrip.c:2876)
close_nocancel (in kernel) (kern_descrip.c:2803)
unix_syscall64 (in kernel) (systemcalls.c:382)
hndl_unix_scall64 (in kernel) + 22
```

So my hypothesis was partially right - it's definitely crashing in `vnode_getattr()`. However, the NULL pointer crash is ultimately happening in `vfs_context_ucred()` which in turn can only happen if it's passed a NULL `vfs_context`. So presumably we're passing that to `vnode_getattr()` - Apple's file systems evidently can handle this, but FUSE cannot. So there are really 2 issues here:

- [ ] Unlike the vnode handler, the fileop handler (`ShouldHandleFileOpEvent()`) isn't checking for allowed file systems.
- [ ] We're playing fast and loose with NULL `vfs_context`s.

The first is easily fixed, the second looks straightforward, but I'm not convinced we should simply be passing through the caller's `vfs_context` - we don't really want the security checks for the normal user to be applied to our metadata queries, so we should be using a root user/kernel level context of some kind. I'll look into this.

**Comment by pmj** [comment]
@hemancuso I've pushed the first part of the fix to my branch at https://github.com/pmj/VFSForGit/tree/fileops-on-allowed-filesystems which should at least get rid of your KP. Let me know if it does indeed resolve the problem, thanks!

**Comment by pmj** [comment]
I believe this bug should now be squashed. There was the filesystem whitelist which went in a few weeks ago, and I've checked all the vfs_context_t uses to make sure they could no longer be NULL.
