### ISSUE TITLE
Mount verb succeeds when ProjFS is not enabled

### ISSUE THREAD

**Issue by derrickstolee** [Microsoft/VFSForGit#347]
It is possible to get into a state where the ProjFS driver is not enabled but the mount verb succeeds (the mount process then has trouble initializing placeholders). This may only happen for new clones, but requires investigation.

**Comment by wilbaker** [comment]
A few updates on what happened (from log files):

- prjflt service was running, but the native ProjectedFSLib.dll was missing
- Somehow ProjectedFSLib.dll was later present in C:\Windows\System32, but it did not appear that GVFS.Service did this.
- Writing placeholders failed with 80070057(InvalidArg), suggesting that the ProjectedFSLib.dll that was copied into System32 was incompatible with the prjflt.sys present on the system.

Next step is to follow up with the ProjFS team and see if they have any recommendations on checking if the .sys and .dll are compatible.

**Comment by wilbaker** [comment]
Closing this bug as per the logs the ProjFS service was running which allowed the mount verb to succeed.
