### ISSUE TITLE
Build Mac installer

### ISSUE THREAD

**Issue by jrbriggs** [Microsoft/VFSForGit#393]
We'll use this issue to talk through options for the Mac installation experience.

**Comment by alameenshah** [comment]
#### Target Users
1. Internal VFSForGit developers (for this sprint - ending 11/01/2019.)
2. Office team, Mac users.
#### Requirements
1. A shell script that creates the VFSForGit Mac installer. This script can be used in the CI build machines. (for this sprint)
2. VFSFotGit Mac installer - installs VFSForGit Mac assemblies & PrjFSKext.kext.
3. VFSFotGit Mac installer - could be invoked from the command line using Terminal or a shell script. Would also provide a Installation Wizard UI (like VFS For Git Windows installer.) (for this sprint)
4. Nice to have - Uninstaller script.
#### Dependencies
1. Git for Windows installer on the Mac.
2. GCM installer for Mac.
3. Java 6 (for GCM).
During the prototyping this sprint, I will experiment and see if it is possible to combine the installers for dependencies into a single metapackage installer. 
#### VFSGit Mac installer - What to install
1. All VFSForGit assemblies in the Publish folder produced by the CI build scripts (for this sprint.)
2. PrjFSKext.kext (for this sprint)
3. All scripts there is today needed to load PrjFSKext.kext and clone a repo (for this sprint).
4. GCM - using GCM installer for Mac
5. Git for Windows - using Git for Windows installer.
#### Goal for this sprint
Build a prototype installer – the goal is to help identify the right tools, alternative options & uncover any hidden issues. The installer would install all artifacts in the “Publish” directory and PrjFSKext.kext along with the existing scripts needed to load the Kext and clone a repo. The prototype installer will be for internal use only and not be released in GitHub.

**Comment by alameenshah** [comment]
> > During the prototyping this sprint, I will experiment and see if it is possible to combine the installers for dependencies into a single metapackage installer.
> 
> It is definitely possible (and in fact standard practice) to place one or more .pkg installer packages produced by `pkgbuild` into a scripted, customised installer .pkg using `productbuild`. I'm not sure what happens if you try to nest one of these into another .pkg, however.
> 
> > **What to install**
> > […]
> > 2. PrjFSKext.kext (for this sprint)
> 
> Installing kexts isn't really any different from installing anything else below `/Library/` with a pkg created with `pkgbuild`. If you have any questions, I might be able to help though as I've built quite a few kext installer packages over the years.

Thank you Phil. Could you please take a look at this PR https://github.com/Microsoft/VFSForGit/pull/438. It installs the Kext as well. Appreciate your feedback.
