### ISSUE TITLE
Use `GitIndexGenerator` to verify tree closure on clone

### ISSUE THREAD

**Issue by derrickstolee** [Microsoft/VFSForGit#397]
On a fresh clone, we perform a `git checkout` before creating our virtualization environment, and that requires that we already have all trees that are reachable from the commit's root tree on disk. This may not be the case if we have another enlistment for the same remote.

Our current solution checks the result of `git checkout` to see if we should force re-downloading the trees at that commit. @sanoursa thinks we can use `GitIndexGenerator` instead.

**Comment by jrbriggs** [comment]
I'm not sure what additional value using `GitIndexGenerator` would provide in this scenario, and I think we have bigger fish to fry. Closing this until we find a flaw with the current implementation.
