### ISSUE TITLE
Harden InProcessMount enlistment/mount id handling

### ISSUE THREAD

**Issue by jrbriggs** [Microsoft/VFSForGit#398]
Rather than silently ignoring missing config values, we should:
- pull enlistment id from the repometadata and rewrite the config setting
- generate a fresh mount id and rewrite the config setting.

**Comment by kewillford** [comment]
@jeschu1 I know that you did some work around this after my initial implementation.  Is this still outstanding work that we need to do to make it better?  Is there other work that we still need to do to make these ids more reliable?

**Comment by jeschu1** [comment]
@kewillford the process we have seems pretty reliable.  We may want to add EnlistmentId/MountId on Dehydrate, but that seems like a separate issue.

**Comment by jrbriggs** [comment]
Sounds like this issue can be resolved. Please reactivate if you disagree @kewillford @jeschu1
