### ISSUE TITLE
`gvfs config [nonexistant key]` should exit with code 1

### ISSUE THREAD

**Issue by jrbriggs** [Microsoft/VFSForGit#402]
To be consistent with Git, we should not print a blank line and we should exit with a non-zero return value.

**Comment by alameenshah** [comment]
Notice the extra line after the call to gvfs config, contrasted with no output with the call to git config.
 
D:\dev\VFSForGitYaml\src [10/17 1:20:51P] [yaml]
λ git config notfound.notfound
D:\dev\VFSForGitYaml\src [10/17 1:20:55P] [yaml]
λ gvfs config notfound.notfound
 
D:\dev\VFSForGitYaml\src [10/17 1:21:03P] [yaml]
λ
 
1. So let’s make sure we set exit code to 1 when we don’t find a key
2. and then don’t print the extra blank line. We’ll keep the 0 exit code when we find the key.
