### ISSUE TITLE
Clone  to specified folder crashes

### ISSUE THREAD

**Issue by OsirisTerje** [Microsoft/VFSForGit#440]
I am cloning a new empty repo into a specified folder. The clone command fails with "The given key was not present in the dictionary"

![image](https://user-images.githubusercontent.com/203432/47711367-5b6c4600-dc35-11e8-9528-6199c31f6769.png)

Last part of the long line:
![image](https://user-images.githubusercontent.com/203432/47711417-7c349b80-dc35-11e8-9f6c-2cbe3b1af471.png)

**Comment by sanoursa** [comment]
You said you're cloning a "new empty repo" which sounds like you're hitting https://github.com/Microsoft/VFSForGit/issues/58. Please reactivate if I misunderstood that.

**Comment by OsirisTerje** [comment]
That's right, it is the same issue.  Understand error messages are not high prio right now, but over some time I hope you get out a more meaningful error here.  :-)
