### ISSUE TITLE
TryGetFromGitConfig should not treat warning strings as errors

### ISSUE THREAD

**Issue by wilbaker** [Microsoft/VFSForGit#471]
There are a few places in the code that read from git config files like this:

```
GitProcess.Result result = git.GetFromConfig(configName);
if (result.HasErrors)
{
    if (result.Errors.Any())
    {
        error = "Error while reading '" + configName + "' from config: " + result.Errors;
        return false;
    }

    // Git returns non-zero for non-existent settings and errors.
    return true;
}
```

This check can cause VFS4G failures when trying to read non-existent config entries.

*Example*

> Failed to determine GVFS timeout and max retries: Error while reading 'gvfs.max-retries' from config: warning: could not open '\\.\pipe\git' for tracing: No such file or directory

**TBD**

- Will git always prepend warnings with "warning"?
- We need to ensure that if there are multiple lines written to `stderr`(some warnings and some errors, that VFS4G *does* fail)

**Comment by jrbriggs** [comment]
Closed with #478
