### ISSUE TITLE
`gvfs upgrade --confirm` does not preserve custom system level git config settings

### ISSUE THREAD

**Issue by wilbaker** [Microsoft/VFSForGit#485]
`gvfs upgrade --confirm` results in any custom --system level config settings being removed.

On Windows these settings are stored in `C:\Program Files\Git\mingw64\etc\gitconfig`

**Comment by dscho** [comment]
Do we really want to do that? IMO that system config is the *system* config, I would *not* expect the user to change it. If the user wants to have some system-level control, they should change `C:\ProgramData\Git\config`.

**Comment by jrbriggs** [comment]
Resolved by #748
