### ISSUE TITLE
Installation instructions for Mac do not work

### ISSUE THREAD

**Issue by adamhowardprice** [Microsoft/VFSForGit#486]
Following the installation instructions for Mac up until running `./Scripts/Mac/BuildGVFSForMac.sh` and then I get this error:

```
/usr/local/share/dotnet/sdk/2.1.403/Microsoft.Common.CurrentVersion.targets(4544,5): error MSB3030: Could not copy the file "/Users/adamprice/Code/VFSForGit/BuildOutput/ProjFS.Mac/Native/Build/Products/Debug/libPrjFSLib.dylib" because it was not found. [/Users/adamprice/Code/VFSForGit/src/GVFS/GVFS.Platform.Mac/GVFS.Platform.Mac.csproj]

Build FAILED.

/usr/local/share/dotnet/sdk/2.1.403/Microsoft.Common.CurrentVersion.targets(4544,5): error MSB3030: Could not copy the file "/Users/adamprice/Code/VFSForGit/BuildOutput/ProjFS.Mac/Native/Build/Products/Debug/libPrjFSLib.dylib" because it was not found. [/Users/adamprice/Code/VFSForGit/src/GVFS/GVFS.Platform.Mac/GVFS.Platform.Mac.csproj]
    0 Warning(s)
    1 Error(s)
```

When I open `GVFS.Platform.Mac.csproj` I see that the three Project dependencies are red (not found).

**Comment by nickgra** [comment]
I've seen this issue before on machines where Xcode has a different DerivedData location than the default (Unique). Can you check in Xcode > Preferences >Locations > DerivedData that Unique is selected?

Alternatively, you can look at the location where this dylib is actually being built by navigating to PrjFSLib > Products > libPrjFSLib.dylib in the Xcode UI which will help debug this further.

**Comment by adamhowardprice** [comment]
Thanks :)
