### ISSUE TITLE
GVFS should use http client SSL authentication settings from git config

### ISSUE THREAD

**Issue by turbonaitis** [Microsoft/VFSForGit#487]
Git config has many http configuration items in it, some of them authentication related (https://git-scm.com/docs/git-config#git-config-httpemptyAuth). The relevant ones to our use case are these:
- `http.sslCert` - specifies client SSL certificate
- `http.sslKey` - specifies the private key for the client SSL certificate
- `http.sslCertPasswordProtected`

**Comment by turbonaitis** [comment]
Thinking about implementation - currently the simplified authentication flow is this:
* GVFS tries to access server anonymously. If that succeeds, we continue without user credentials
* If anonymous request fails with `Unauthorized`, we try to get credentials from `git credential` and use them 

Now, with these SSL settings:
1. Do we want to still try anonymous request, before loading the configured certificate? I'd say yes, if we can get away with anonymous access, it'd be great to avoid the cost of getting the certificate etc. 
2. Do we try to make a request with just the configured SSL certificate, or do we still set authorization header from `git credential`? My suggestion is to try to use username/password from `git credential` immediately along with the certificate, otherwise we'll end up with the question which combinations of client cert + username/passwrod we use and in what order.

**Comment by turbonaitis** [comment]
After looking into how git uses those settings, I actually think, that we should always send the ssl client certificates, if configured, as this is how git behaves. It also simplifies the code quite a bit.

**Comment by jrbriggs** [comment]
Closing this issue: the PR was merged.
