### ISSUE TITLE
Deleting a previously mounted VFS for git enlistment

### ISSUE THREAD

**Issue by sanderaernouts** [Microsoft/VFSForGit#503]
On our private Azure DevOps build agent we use `gvfs.exe clone` to clone certain repositories. After we are done with the repo we use `gvfs.exe unmount` to "release" the files in the vfs for git enlistment. When the next build comes on the same server it will clean out the folder that contains the repository that was previously cloned with `gvfs.exe`. We have noticed that you must delete the files and directories in this directory in a very specific way else files or empty directories may stay behind and the next `gvfs.exe clone` command will fail saying you cannot clone into an existing repository. Also we cannot use the default clean step provided by the Azure DevOps build pipelines because it will fail saying it cannot delete the VFS for git enlistment directory because it is not empty.

So we have disabled that step and currently we are using this script:
```bat
echo "Checking for existing directories inside:" $(TargetDirectory)
if not exist $(TargetDirectory) goto  nodir
echo $(TargetDirectory)
del /q /a $(TargetDirectory)\*
echo "Deleted subdirectories directly, continuing with subdirs that were not fully deleted"
for /d %%x in (.\*) do @rd /s /q "%%x"
:nodir
```

As you can see it is a two step process to delete the directory and then run another command to delete whatever was left behind. I see the same behaviour locally sometimes meaning that I have to delete a folder, then go into that folder to delete the subfolders and then try and delete the original folder again.

Is this a known issue/behaviour or am I not releasing the vfs git enlistment properly by only using `gvfs.exe unmount`?

**Comment by sanderaernouts** [comment]
Had the same issue again today, is there anyone who has the same issue?

**Comment by sanoursa** [comment]
The correct way to delete a VFSForGit repo is to first unmount it with `gvfs unmount`, and then delete it, which you seem to be doing. Once you've unmounted, nothing from VFSForGit or ProjFS should be preventing the delete.

The fact that your first delete is failing is most likely caused by other tools having open handles to files within your repo. I suggest using `handle.exe` to see if there are any open handles to pinpoint what tool might be doing that.

**Comment by sanderaernouts** [comment]
I made a small change to my clean step so that is logs the contents of the directory after cleaning. It actually looks like there are files in the `.gvfs` folder that remain behind:
![image](https://user-images.githubusercontent.com/6184673/49072104-cc504f00-f22f-11e8-99aa-e77886a97fc4.png)

**Comment by sanderaernouts** [comment]
I noticed that in this particular case the .gvfs folder is hidden. I have updated my delete script to include hidden files/directories. It looks like GVFS made this directory hidden at some point. Is this expected or is this a known issue?

**Comment by sanderaernouts** [comment]
I updated my script to do the following:
```
echo off
set folder="$(TargetDirectory)"

if not exist %folder% goto  nodir

pushd %folder%
echo Cleaning directory %folder%
for /F "delims=" %%i in ('dir /b /s /A') do (rmdir "%%i" /s/q || del "%%i" /a/s/q)
echo Contents after cleaning:
dir /s/b
popd

goto eof
:nodir
echo Skipping directory %folder%, because it does not exist.
:eof
```

This will also delete hidden files and folders. Running builds now to see if this works

**Comment by sanoursa** [comment]
Yes, the `.gvfs` folder is hidden intentionally, and it has been for a long time.

I'm curious, why aren't you just doing `rmdir /s` on the root folder directly? You shouldn't have to care if subfolders are hidden or not.

**Comment by sanderaernouts** [comment]
In some cases I use the $(Build.SourcesDirectory) on Azure DevOps as root if I delete that folder I need to recreate it. I do this to prevent paths from getting too long. The strange thing is though that I have multiple builds that use the same setup and only 1 is giving issues. But that must be unrelated to GVFS. 

I'm closing the issue because my questions as to why this is happening have been answered.
