### ISSUE TITLE
Version is reported as 0.0.0.0

### ISSUE THREAD

**Issue by jrbriggs** [Microsoft/VFSForGit#518]
On macOS, the version is being reported incorrectly:
```
jrbriggs@jrbriggs-mac:~/test$ gvfs version
GVFS 0.0.0.0
```

**Comment by wilbaker** [comment]
This might be the same underlying issue as #95

**Comment by wilbaker** [comment]
See also:

https://stackoverflow.com/questions/42138418/equivalent-to-assemblyinfo-in-dotnet-core-csproj
https://stackoverflow.com/questions/39163558/do-i-need-assemblyinfo-while-working-with-net-core

One issue preventing the version from getting stamped on the Mac is that `GVFS.PreBuild` is not getting built (and it generates CommonAssemblyVersion.cs).
