### ISSUE TITLE
Mac: Determine a better default location for the local cache

### ISSUE THREAD

**Issue by jrbriggs** [Microsoft/VFSForGit#519]
Currently we try to place the cache at /.gvfsCache. It should go to inside the user's home folder instead.

**Comment by derrickstolee** [comment]
I think this is the best default. Users who have multiple drives and want to specify the location of the shared cache can use `--local-cache-path` on clone.

**Comment by mjcheetham** [comment]
Might also be worth looking at improving the path expansion of `--local-cache-path` since currently if you use `gvfs clone --local-cache-path=~/.gvfsCache <url>` we don't create the cache in ~/.gvfsCache, but instead create it at ./~/.gvfsCache.

**Comment by jrbriggs** [comment]
@mjcheetham interesting -- I can't repro that. But I also omit the =. I wonder if that is the culprit.

**Comment by derrickstolee** [comment]
Yeah, the `=` pattern is something in the `git` option parsing, but not our verbs.

**Comment by sanoursa** [comment]
Re: expansion - we don't do any expansion today, the shell handles it for us. But that requires that it be at the beginning of a string, so @jrbriggs is correct that inserting the `=` breaks that. I'm not sure that we should do any expansion ourselves, I think that is the role of the shell, but if we want to do anything there, we should make sure it is applied to all path parameters, and it should be a separate issue.

Re: the topic of this issue, @jrbriggs I agree that the `/.gvfsCache` is not the correct location, but neither is `~/.gvfsCache`. I believe this is covered by TODOs in the code, but our intent here is to discover the root of your current volume and place the cache there. The scenario to think about is: "I just went and bought a giant SSD to host my repo; why are you putting the cache on my puny drive that happens to host my home folder?"

**Comment by wilbaker** [comment]
> The scenario to think about is: "I just went and bought a giant SSD to host my repo; why are you putting the cache on my puny drive that happens to host my home folder?"

Another scenario is the shared machine scenario.  If a team has a handful of Macs that are shared by multiple people, ideally they would all share the same .gvfsCaches.

**Comment by jrbriggs** [comment]
@sanoursa @wilbaker those are both good scenarios to consider, but I think they're both lower priority than having the happy path be predictable.

I propose we use this issue to update the default on macOS to be ~/.gvfsCache, which at least allows clone to succeed with no special parameters. That's objectively better for early adopters than the state we're in today. We can file a subsequent issue to track lifting that cache to the volume root and managing acls on that path.

Thoughts?

**Comment by turbonaitis** [comment]
Another good option, if we want to share cache between users, is to put it somewhere under `/var` ( like `/var/cache/.gvfsCache`), as that is a global location, that is meant for such data (https://www.granneman.com/tech/linux/thelinuxenvironment/topleveldirectories). Also, allowing to change it by setting an environment variable (or modifying git config) globally would be great, as passing cache location on each clone is certainly not a great UX.

**Comment by wilbaker** [comment]
Based on the discussion here:

https://unix.stackexchange.com/questions/23156/can-i-safely-remove-var-cache

I hesitate to put the directory inside `/var/cache` as VFS4G might have sub-optimal recovery if someone/something starts deleting pack files from inside the `.gvfsCache` folder.

> I propose we use this issue to update the default on macOS to be ~/.gvfsCache, which at least allows clone to succeed with no special parameters. That's objectively better for early adopters than the state we're in today. We can file a subsequent issue to track lifting that cache to the volume root and managing acls on that path.

@jrbriggs for now my plan is to go with the approach you've suggested (including filing a follow up item to investigate the best location that can be shared by users).

\+ @nickgra for his thoughts

**Comment by wilbaker** [comment]
One more data point:  In some basic testing I've found that by default root access is required to create subfolders inside `/var`.

Perhaps the installer could create a `/var/VFSForGit/.gvfsCache` directory with permissions such that non-root users could write into it?

If we can get this right from the start we'll avoid having to write (potentially complicated) migration/upgrade code later.

\+ @alameenshah and @pmj for their thoughts as well on the best place to put this directory.

**Comment by nickgra** [comment]
Historically, customers of our large repository put their clones of it on separate external drives (or partitions of a large drive). A sizable percentage of users have a very small OS partition (and thus home folder) so putting it in `~` might fill up their drive quickly when cloning a repo that requires VFS4G.

> Perhaps the installer could create a /var/VFSForGit/.gvfsCache directory with permissions such that non-root users could write into it?

I like this more than the home folder idea (solves sharing between users) but I believe /var will always be in the boot volume so it won't help if it's very small.

Optimizing for those first customers, I think the best solution for them is to put the cache in `/var/VFSForGit/.gvfsCache` if the clone is going to be in the boot volume or put it in the root of the volume if it's an external drive/partition? That should let us avoid the problem of writing a folder into the top level `/` folder which requires root and is a rather nasty thing to do.

This does require two code paths though so I'm not convinced it's the best solution I'm afraid.

**Comment by turbonaitis** [comment]
So why not chose a reasonable default, such as `/var/VFSForGit/.gvfsCache`, and allow to override it with an environment variable? Determining the "root of the volume" might be non trivial and brings little benefit over a clear and well documented way of overriding the default with an environment variable.
