### ISSUE TITLE
Opening ProjFS.xcworkspace on un-enumerated workspace causes execute bit to not be set

### ISSUE THREAD

**Issue by jrbriggs** [microsoft/VFSForGit#520]
Repro steps, follow exactly:
1. Clone VFSForGit in VFSForGit on Mac
2. Open ProjFS.xcworkspace via Xcode's open dialog
3. Edit a file (might not be necessary)
4. Check mode bits in Scripts/Mac

Expected: 755
Actual: 644

**Comment by jeschu1** [comment]
No longer repros so closing
