### ISSUE TITLE
Mac: Git checkout and merge sometimes produce bad results

### ISSUE THREAD

**Issue by wilbaker** [Microsoft/VFSForGit#522]
Note that both of these issues reproduce without VFS4Git

**Merge**

See https://github.com/Microsoft/git/issues/63

**Checkout**

1. `git clone https://github.com/wilbaker/VFSForGit`
2. `git checkout dont_assert_on_file_attributes_merge_weirdness`
3. `git status`
4. `git checkout bad_checkout_master`
5. `git status`

Repeat steps 2 through 5 until `git status` shows a bunch of modified files.

**Comment by jrbriggs** [comment]
Closing for now for lack of a solid repro. We'll reactivate if one becomes available. Also, haven't seen this since we went to Git 2.20 series.
