### ISSUE TITLE
Mac: Use the WILL_RENAME file op event on Mojave to determine if PreDelete is part of a rename

### ISSUE THREAD

**Issue by wilbaker** [microsoft/VFSForGit#526]
In Mojave Apple added a new WILL_RENAME file op event that can be used to determine if DELETE vnode operations are part of a rename.

VFS4G should use this file op event to determine if it needs to hydrate a file and either expand/hydrate directories (or block them from being deleted)

**Comment by wilbaker** [comment]
Another option here is that WILL_RENAME could be used to determine if we should prevent the rename of directories to match the behavior on Windows

**Comment by wilbaker** [comment]
@pmj before starting this work please confirm with @jrbriggs that we have confirmation that we can set Mojave as the minimum supported macOS version.

/cc: @nickgra

**Comment by pmj** [comment]
It looks like the `KAUTH_FILEOP_WILL_RENAME` -> `KAUTH_VNODE_DELETE` pairing is reliable (i.e. we *always* get a `KAUTH_VNODE_DELETE` after a `KAUTH_FILEOP_WILL_RENAME`), and intentionally so:

https://github.com/apple/darwin-xnu/blob/a449c6a3b8014d9406c2ddbdc81795da24aa7443/bsd/vfs/vfs_subr.c#L6255

I've not just taken the comment at face value but looked at the code for `vnode_authorize()` and it appears each registered vnode listener kext does indeed get a chance to see the event even if an earlier kext's listener has already denied the operation.

This is good news, as it simplifies the implementation somewhat.

**Comment by pmj** [comment]
With #1193 merged, there's nothing left to do here as far as I'm aware.
