### ISSUE TITLE
Windows: Switch to using Utils.FileNameCompare when sorting file names and upgrade to ProjFS version 2019.411.1 

### ISSUE THREAD

**Issue by wilbaker** [Microsoft/VFSForGit#551]
A few changes are needed for this work item:

1. Pick up ProjFS version 2019.411.1 (see #1025)

2. [`CaseInsensitiveCompare`](https://github.com/Microsoft/VFSForGit/blob/d49b67d0ec78696cf5de80925a994feb47f6d251/GVFS/GVFS.Virtualization/Projection/GitIndexProjection.LazyUTF8String.cs#L123) should fall back on [`FileNameCompare`](https://github.com/Microsoft/ProjFS-Managed-API/blob/9ac27a91830cd3597f5f6249ffd18ff0eba141bf/ProjectedFSLib.Managed.API/Utils.h#L77) instead of `string.Compare`

3. `CaseInsensitiveCompare` should do an up-case comparison on Windows (like `FileNameCompare`) so that files like those mentioned in #504 are handled correctly.

4. Add functional test(s) that reproduce the file name sorting issue and confirm they pass after the above fixes.

Note that items 2 and 3 above might require that file name sorting logic be moved into `GVFSPlatform`.

**Comment by jrbriggs** [comment]
@wilbaker What is the impact of not returning the enumeration in the same order NTFS would?

**Comment by wilbaker** [comment]
> @wilbaker What is the impact of not returning the enumeration in the same order NTFS would?

@jrbriggs the same file could appear twice in the enumeration results (with one set of values coming from disk and another set coming from VFS4G's projection).  The duplicated entries could have different attributes (e.g. size) if the file on disk has been modified.

Based on the repro from the original bug (#504), filenames with underscores are particularly problematic (see example [here](https://github.com/dcou/prjflt_bug_repros/blob/e18919c665c3fdf2e860ab6af6007b9f2015b3f4/prjflt_bug_repros.cpp#L366))

**Comment by wilbaker** [comment]
There has been a new release to the managed API:

https://github.com/Microsoft/ProjFS-Managed-API/pull/27

So we might as well pick that up as part of these changes as well.

**Comment by jeschu1** [comment]
@wilbaker, since we confirmed we don't have a bug in the way we currently order and we'd need wider changes than just Utils.FileNameCampare to replace our current functionality, should we close this issue?

**Comment by wilbaker** [comment]
@jeschu1 yep I think we can close this.  #1073 has been merged to upgrade to 2019.411.1 and I agree that we don't need to switch to `Utils.FileNameCompare`.
