### ISSUE TITLE
Mac: Investigate why BashRunner.DeleteDirectoryWithUnlimitedRetries is hanging only in GVFSFunctionalTestEnlistment

### ISSUE THREAD

**Issue by nickgra** [microsoft/VFSForGit#554]
In an earlier PR, @wilbaker discovered this hang when standing up GVFS.Hooks on MacOS. Upon doing some code cleanup, I tried folding all uses of this code together. This worked fine for the uses in SharedCacheTests and FastFetchTests, but not for GVFSEnlistmentTests.

**Comment by wilbaker** [comment]
@jrbriggs I was just looking through the backlog and this issue caught my eye.  I think we should check if these hangs are still happening and if so work to get to the bottom of them.

I'll move this from "macOS Next" to M154, but please feel free to re-assign it if you disagree.
