### ISSUE TITLE
Mac: Add unit tests for kext code

### ISSUE THREAD

**Issue by wilbaker** [Microsoft/VFSForGit#561]
Add unit test infrastructure (and tests) for the ProjFS kext code.

**Comment by wilbaker** [comment]
@jrbriggs @jeschu1 I think we can close this issue.  The unit test infrastructure is in place, and I think we have more specific issues tracking the remaining work?

**Comment by jrbriggs** [comment]
I agree, closing the issue.

/cc @wilbaker @jeschu1
