### ISSUE TITLE
Mac: ProjFS logger should re-connect to the kext when the kext is unloaded\reloaded

### ISSUE THREAD

**Issue by wilbaker** [Microsoft/VFSForGit#564]
Details from @pmj: 
> I think the prjfs-log based fix is probably the cleanest solution to this. It makes sense to unload and re-load the kext as part of our functional testing, and trying to intertwine that with stopping and starting the logger tool seems unnecessarily complicated. In case you want to experiment with this before I get around to fixing it myself: essentially, the IOServiceGetMatchingService() call needs to be replaced with a IOServiceAddMatchingNotification() setup which continuously monitors the system for matching IOService objects appearing.

**Comment by pmj** [comment]
The implementation of this in PR #566 seems to be working well now.
