### ISSUE TITLE
Mac: Update xattr names, DNS bundle identifier, and magic number in header

### ISSUE THREAD

**Issue by sanoursa** [Microsoft/VFSForGit#584]
We need to drop the "gvfs" part of the xattr names anyway, might as well do it before we get any real users. 

And I'm not sure I have a strong opinion on what the magic number in the header ought to be. Is the current value good enough?

**Comment by pmj** [comment]
There's also the reverse DNS bundle identifier for the kext and the corresponding class names which still use `io.gvfs` and `io_gvfs_`, respectively. (Doing a find-all in Xcode on those strings should bring up all instances.)

**Comment by pmj** [comment]
I've noticed that some identifiers use `com.vfsforgit.` while others use `org.vfsforgit.` Which one are we standardising on?

(I'm having a go at implementing this fix as I've got a bit of time while waiting on PR feedback for all my other open tasks.)

**Comment by pmj** [comment]
Thanks to PR #751, the only remains of the `io.gvfs.` prefix are in legacy-supporting/upgrade code which is on track to be removed somewhere down the line (#891).
