### ISSUE TITLE
What hosts support VFS For Git?

### ISSUE THREAD

**Issue by tomspilman** [Microsoft/VFSForGit#593]
Is there any list of hosts that currently support VFS For Git?

These are the only ones i know currently support it:

  - Visual Studio Team Services

These do not as of this time:

  - GitHub
  - Gitlab

These i don't know:

   - Bitbucket

Are there any others?

**Comment by jrbriggs** [comment]
Right now Azure Repos (formerly VSTS) is the only service with VFS for Git support that's available. I believe GitHub is currently working on adding that support. Bitbucket supports it via an addin for Bitbucket server, but they don't support it on the Bitbucket service. I think GitLab has it on their backlog but I don't know the status.

**Comment by damoando4** [comment]
We have been testing our large repos using VFS for Git on Bitbucket. We haven't seen any server related issues. Atlassian have not been forthcoming on any plans to officially confirm the add-in is fully supported. Strangely they want confirmation from customers that it works before providing such a statement.  There is no enablement of Bitbucket smart mirror which is a significant issue for geographically dispersed teams requiring to work with large repos.

**Comment by jrbriggs** [comment]
Closing, since I think this question has been answered.
