### ISSUE TITLE
Unable to query /gvfs/config

### ISSUE THREAD

**Issue by damoando4** [Microsoft/VFSForGit#595]
Have been hitting an issue with a version of gvfs which previously worked against an internal Bitbucket instance which had the gvfs add-in installed. We then tried against an Azure repo which resulted in the same error:

Clone parameters:
Repo URL: https://damoando@dev.azure.com/damoando/firstProject/_git/firstProject
Cache Server: Default
Destination: c:\Users\naraprab\firstProject
Authenticating...Succeeded
Querying remote for config...Failed
Unable to query /gvfs/config

Log file shows a successful authentication followed by an error sending the QueryGvfsConfig request.

This is a pre ProjFS version of gvfs: GVFS 1.0.17318.1

Thanks

**Comment by jrbriggs** [comment]
Please try with the remote as https://damoando.visualstudio.com/firstProject/_git/firstProject. I don't think your version knows how to talk to dev.azure.com.

**Comment by damoando4** [comment]
Closing as this error is the response to http get issue. We were also seeing it when attempting to clone a repo from an internal instance of Bitbucket. This was fixed by adding the Bitbucket root and intermediate certificates to the client device.  We believe the gvfs clone of the VSTS repo is failing due to firewall config.
