### ISSUE TITLE
Mac: Audit all settings in TrySetRequiredGitConfigSettings and see if they make sense on Mac

### ISSUE THREAD

**Issue by wilbaker** [microsoft/VFSForGit#603]
Check all of the settings in `TrySetRequiredGitConfigSettings` and see if they make sense on all platforms, or if some are Windows (or Mac) specific.

**Comment by kewillford** [comment]
Here is a list of the config value that get set as of 2-12-2019 and information on each one.  At this point I don't think there are any that need different values aside from the ones that are already different for each platform.

Command|Windows|Mac|Comments
-|-|-|-|
am.keepcr|true|true|Does not remove \r during am
checkout.optimizenewbranch|true|true|Perf
core.autocrlf|false|false|stop line ending conversions
core.commitGraph|true|true|Perf
core.fscache|true|true|Perf
core.gvfs|true|true|
core.multiPackIndex|true|true|Perf
core.preloadIndex|true|true|Perf
core.safecrlf|false|false|stop check for CRLF conversions
core.untrackedCache|false|false|Perf
core.repositoryformatversion|0|0|?
core.filemode|false|true|File system support file mode
core.bare|false|false|Force repo to not be seen as bare
core.logallrefupdates|true|true|debugging
core.virtualizeobject|true|true|
core.virtualfilesystem|
core.hooksPath|||where to looks for hooks
credential.useHttpPath|true|true|Need for credential helper
credential.validate|false|false|Credential helper
diff.autoRefreshIndex|false|false|Perf
gc.auto|false|false|Perf
gui.gcwarning|false|false|stop warning to run gc when using git gui
index.threads|true|true|Perf
index.version|4|4|index size
merge.stat|false|false|Perf
merge.renames|false|false|Perf
pack.useBitmaps|false|false|
pack.useSparse|true|true|Perf
receive.autogc|false|false|Pref
reset.quiet|true|true|Correctness with post-index-changed hook
status.deserializePath|||Perf

**Comment by jrbriggs** [comment]
I don't think we need further action here.
