### ISSUE TITLE
Each maintenance step should implement TimeBetweenRuns & TimeFilePath

### ISSUE THREAD

**Issue by jeschu1** [Microsoft/VFSForGit#617]
It should instead be in PrefetchMaintenanceStep

**Comment by jeschu1** [comment]
protected virtual TimeSpan TimeBetweenRuns { get; } 
protected virtual string TimeFilePath { get; set; }

Update to abstract and have all steps implement/use.

**Comment by derrickstolee** [comment]
The base issue here was resolved by #635. The `TimeBetweenRuns` and `TimeFilePath` that follows are not done.

**Comment by jeschu1** [comment]
This is no longer a priority.
