### ISSUE TITLE
Update Prefetch Step To use the Timestamp file for Time between runs

### ISSUE THREAD

**Issue by jeschu1** [Microsoft/VFSForGit#621]
protected virtual TimeSpan TimeBetweenRuns { get; }
protected virtual string TimeFilePath { get; set; }

Update to abstract and have all steps implement/use.

**Comment by derrickstolee** [comment]
Thanks for filing this issue, @jeschu1. I think I found an easier way to fix the deeper issue.

The deeper issue is this: as we start running expire/repack to clean up the pack-files, we may replace the most-recent prefetch pack and remove its timestamp.

The real fix actually came from a mailing list suggestion: we should honor the ".keep" files. If a pack-file <file>.pack has an associated <file>.keep, then `git` should never delete that pack. We can write a .keep file for our most-recent timestamp and then remove it after we have a more-recent pack. I'm working on a similar idea for the pack-file maintenance part of #488.
