### ISSUE TITLE
Publish releases on macOS

### ISSUE THREAD

**Issue by Jarred-Sumner** [microsoft/VFSForGit#629]
I'd love to try out VFS for Git on Mac and see what the performance difference looks like on a larger repo.

However:
- Uncomfortable with disabling SIP on my work laptop
- Installing Visual Studio for Mac just to try this out is a little too much

The easiest thing on my end would be if I could do something like ```brew install vfs-for-git```. Second easiest would be a DMG with an installer I could download from the Releases section on this repo.

Is there an issue I can track that will let me know when pre-built releases for Mac are published?

**Comment by Jarred-Sumner** [comment]
> I'd love to try out VFS for Git on Mac and see what the performance difference looks like on a larger repo.
> 
> However:
> 
> * Uncomfortable with disabling SIP on my work laptop
> * Installing Visual Studio for Mac just to try this out is a little too much
> 
> The easiest thing on my end would be if I could do something like `brew install vfs-for-git`. Second easiest would be a DMG with an installer I could download from the Releases section on this repo.
> 
> Is there an issue I can track that will let me know when pre-built releases for Mac are published?

**Comment by jrbriggs** [comment]
Thanks for interest, @Jarred-Sumner! We're still a ways away from offering pre-built releases of VFS for Git on Mac. Most notably, we need to be signing the kext, tracked by #528. After that we'll be in a state where you won't need to disable SIP so we can offer releases to the general public.

I've retitled this issue as the general tracking issue for offering those releases.

**Comment by sibelius** [comment]
can we install vfs using `brew`?

`brew install vfs`

**Comment by grimreaper** [comment]
> can we install vfs using `brew`?

or macports?

**Comment by mxplusb** [comment]
@jrbriggs what's the state of this issue?

**Comment by kigster** [comment]
> > can we install vfs using `brew`?
> 
> or macports?

Nobody uses macports anymore :)

**Comment by Abszissex** [comment]
After the ticket is now open for 3 years, is there any update on this?

**Comment by vtbassmatt** [comment]
VFS for Git will not be coming to macOS after all. There are several overlapping reasons, but the most relevant is that acceptable performance required a particular set of extensibility points which the macOS platform no longer offers. Instead, we suggest you try out all the performance gains that have upstreamed into Git, like [partial clones](https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/) and [sparse checkouts](https://github.blog/2020-01-17-bring-your-monorepo-down-to-size-with-sparse-checkout/), and possibly also [Scalar](https://github.com/microsoft/scalar).
