### ISSUE TITLE
VFS4G builds failing in VS IDE on Windows

### ISSUE THREAD

**Issue by wilbaker** [Microsoft/VFSForGit#634]
Sample error:

> error MSB4126: The specified solution configuration "|x64" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [C:\github\VFSForGit\GVFS.sln]
1>C:\github\VFSForGit\GVFS\GVFS.Build\GVFS.PreBuild.csproj(185,5): error MSB3073: The command "call C:\github\VFSForGit\GVFS\GVFS.Build\..\..\Scripts\RestorePackages.bat" exited with code 1.

**Comment by jeschu1** [comment]
@nickgra I'm also getting an issue running the unit tests in VS on Windows.  Do you see the same?

```
10>C:\Users\jeschu\gvfs3\BuildOutput\GVFS.Platform.Mac\obj\x64\Debug\netcoreapp2.1\GVFS.Platform.Mac.AssemblyInfo.cs(14,12,14,54): error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute
10>C:\Users\jeschu\gvfs3\BuildOutput\GVFS.Platform.Mac\obj\x64\Debug\netcoreapp2.1\GVFS.Platform.Mac.AssemblyInfo.cs(15,12,15,60): error CS0579: Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute
10>C:\Users\jeschu\gvfs3\BuildOutput\GVFS.Platform.Mac\obj\x64\Debug\netcoreapp2.1\GVFS.Platform.Mac.AssemblyInfo.cs(18,12,18,54): error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute' attribute
10>C:\Users\jeschu\gvfs3\BuildOutput\GVFS.Platform.Mac\obj\x64\Debug\netcoreapp2.1\GVFS.Platform.Mac.AssemblyInfo.cs(19,12,19,52): error CS0579: Duplicate 'System.Reflection.AssemblyTitleAttribute' attribute
```

**Comment by jeschu1** [comment]
> 10>C:\Users\jeschu\gvfs3\BuildOutput\GVFS.Platform.Mac\obj\x64\Debug\netcoreapp2.1\GVFS.Platform.Mac.AssemblyInfo.cs(14,12,14,54): error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute

@derrickstolee and I were both able to fix by deleting the BuildOutput dir
