### ISSUE TITLE
Mac: Terminal is noticeably slower when configured to use git's bash integration 

### ISSUE THREAD

**Issue by wilbaker** [microsoft/VFSForGit#706]
Steps to reproduce:

1. Open Terminal
2. Run the following commands:

```
source /Applications/Xcode.app/Contents/Developer/usr/share/git-core/git-completion.bash
source /Applications/Xcode.app/Contents/Developer/usr/share/git-core/git-prompt.sh
export GIT_PS1_SHOWDIRTYSTATE=true
export PS1='\n[\h:\w$(__git_ps1)]\n \u\$ '
```

3. Navigate to a mounted VFS4G repo
4. Move between different directories in the repo

Observe: Navigating folders is slower than in a native git repo

**Comment by wilbaker** [comment]
You can configure git to trace additional to a log file by running:

`export GIT_TR2_EVENT=an-absolute-path`

Which might provide more hints as to what's going on.

**Comment by jeschu1** [comment]
The issue is that `git diff -no-ext-diff` is called when building the command prompt.  That is by design and will be expensive on a large repository.
