### ISSUE TITLE
VFS4Git should call `git credential approve/reject` after `git credential fill`

### ISSUE THREAD

**Issue by mjcheetham** [Microsoft/VFSForGit#745]
From the [documentation about `git-credential`](https://git-scm.com/docs/git-credential):

> If the action is `fill`, git-credential will attempt to add "username" and "password" attributes to the description by reading config files, by contacting any configured credential helpers, or by prompting the user. The username and password attributes of the credential description are then printed to stdout together with the attributes already provided.
>
> If the action is `approve`, git-credential will send the description to any configured credential helpers, _**which may store the credential for later use**_.
>
> If the action is `reject`, git-credential will send the description to any configured credential helpers, which may erase any stored credential matching the description.
>
> If the action is `approve` or `reject`, no output should be emitted.

Currently we are only calling `git credential fill` without a subsequent `approve` or `reject` from inside of VFS for Git. This leads to a second authentication prompt when `git` operations are called because although we generated the PAT (for Azure Repos), we never instructed GCM to store it.

Due to quirky behaviour of the Windows GCM, credentials _are being stored on a call to `git credential fill`_ (which calls `git-credential-manager get`) without the calls to `approve/reject` as required by the Git usage documentation. The new GCM on macOS follows the `git-credential` API correctly and as such we are forgetting the credential after the initial prompt.

---

Aside: the credential helper API documentation can be found [here](https://git-scm.com/docs/api-credentials). It states that a helper should do the following things when called with each action:

> `get` (called by `git-credential fill`)
> Return a matching credential, if any exists.
>
> `store` (called by `git-credential approve`)
> Store the credential, if applicable to the helper.
>
> `erase` (called by `git-credential reject`)
> Remove a matching credential, if any, from the helper’s storage.

Windows GCM incorrectly combined `store` into the `get` call, and it's `store` (and `erase` in some instances) end up being no-ops.

**Comment by jrbriggs** [comment]
I want to take this change, but let's target the release after the one that we're starting to prepare.

**Comment by mjcheetham** [comment]
> I want to take this change, but let's target the release after the one that we're starting to prepare.

@jrbriggs am I OK to merge this into master now?
