### ISSUE TITLE
Update Git to guard process tree walk from infinite recursion.

### ISSUE THREAD

**Issue by jrbriggs** [Microsoft/VFSForGit#766]
We found a hard-to-reproduce scenario where `trace2_collect_process_info` was stuck in an infinite loop walking the process tree. This issue tracks consuming a fixed version of Git.

**Comment by jamill** [comment]
The fixes for this have been incorporated with

#749 
#779 

@jeffhostetler - I think we can close this out?

**Comment by jrbriggs** [comment]
Closing this out since the PRs have been merged.
