### ISSUE TITLE
GVFS Support for submodules

### ISSUE THREAD

**Issue by ycon-company** [Microsoft/VFSForGit#780]
Hi all & @sanoursa ,

I saw issue #44 about gvfs support for submodules.
Is it still not supported?

Thanks,
Yael

**Comment by jrbriggs** [comment]
Hi @ycon-company, 

We still haven't needed submodules in VFS for Git, so they are still not supported.

**Comment by jrbriggs** [comment]
Closing, as I believe the question has been answered.

**Comment by manandmehta** [comment]
Is the submodules feature in pipeline ? It is an important feature for big projects.
