### ISSUE TITLE
Could not build if System Locale is not English.

### ISSUE THREAD

**Issue by 0xbadfca11** [Microsoft/VFSForGit#8]
Build failure if Control Panel -> Clock, Language, and Region -> Region and Language -> Administrative -> Current language for non-Unicode programs: is not English. Build succeeded when I switched to English (United States).
Build log: https://gist.githubusercontent.com/0xbadfca11/bf4ff1307101a6b187cd31570c2fbd4a/raw/feb4f955576bf40a0d3d14bd399cc9a79c3bdbdc/gistfile1.txt

**Comment by fcharlie** [comment]
save gvlib.h encoding to UTF16LE

**Comment by sanoursa** [comment]
Thanks for the report. We will take a look, but this is a fairly low priority issue since all of our build environments are in English. I'd be happy to take a PR from you as long as it doesn't affect English environment builds.

**Comment by boltomli** [comment]
I guess there won't be PR until the codes in issue #5 are released because the header file looks to be from the package.

**Comment by sanoursa** [comment]
VFS for Git no longer builds the ProjFS native code, so this should no longer be an issue.
