### ISSUE TITLE
git apply does not work with VFS for Git repositories

### ISSUE THREAD

**Issue by turbonaitis** [microsoft/VFSForGit#809]
Git apply fails, because git is trying to compare stat call result from disk with stat information, that is supposed to be in the `.git/index`. GVFS fills those fields with zeroes though, so they never match and `git apply` fails with:
`error: <file in patch>: does not match index`

Either GVFS client needs to be modified to write matching data to index (and then keep it up to date), or git needs to be patched to take this into account, when working with virtualized repositories.

**Comment by turbonaitis** [comment]
This only applies when `--index` is specified.

**Comment by jrbriggs** [comment]
we'll use #1108 for tracking as it has clearer repro steps.
