### ISSUE TITLE
[Linux] Rebase of branch

### ISSUE THREAD

**Issue by kivikakk** [Microsoft/VFSForGit#818]
We've done a rebase of the `features/linuxprototype` branch on top of VFSForGit's current `master` -- feel free to reset your branch pointer to https://github.com/github/VFSForGit/commit/ebec5f12d668025463f08e93fee47b411d6e0c8a if you'd like to take advantage of this!

**Comment by chrisd8088** [comment]
Awesome, thank you @kivikakk, as always!  ✨ ⭐️

**Comment by jrbriggs** [comment]
I've reset `features/linuxprototype` to ebec5f1. Thanks @kivikakk

**Comment by kivikakk** [comment]
Thank you! :heart:
