### ISSUE TITLE
Consume Git with fix for multi-pack-index verify

### ISSUE THREAD

**Issue by jrbriggs** [Microsoft/VFSForGit#844]
Git multi-pack-index verify can produce a false negative when run on an enlistment with a large number of packs. This issue tracks consuming the fix in Git to not exhaust file descriptors.

**Comment by jeffhostetler** [comment]
See https://github.com/Microsoft/git/pull/121

**Comment by jeffhostetler** [comment]
TODO upstream this.

**Comment by jeffhostetler** [comment]
See also https://github.com/Microsoft/git/pull/124
