### ISSUE TITLE
Move all relative path calculations out of the kext and into user mode

### ISSUE THREAD

**Issue by wilbaker** [microsoft/VFSForGit#846]
Follow up work item from discussion in #741

* For the remaining path-based kernel-user messages (in the Fileop handler), we're computing the relative path based on the root's path. This is then typically turned back into an absolute path in the provider. Instead, we could simply send the absolute path from the kext into the provider and generate the relative path where needed, or directly use the absolute path where that's the most convenient.
* If we get rid of the relative path calculation, we can completely get rid of the path field from the virtualisation root struct.

**Comment by wilbaker** [comment]
@pmj was this work item completely resolved by #984? 

Or is some of the work in #985 related to this work item?

**Comment by pmj** [comment]
Yeah, this was all sorted in #984.
