### ISSUE TITLE
Better management of .gvfsCache folder

### ISSUE THREAD

**Issue by sanoursa** [microsoft/VFSForGit#85]
This is just a placeholder issue for now, because we still need to do a lot more thinking about the best solutions here. The problems we've thought about so far:

* The .gvfsCache has no eviction policy, so it will just grow indefinitely. We should think about a good eviction policy, especially for blobs.
* The cache can currently have lots of duplicated objects, especially trees. Need a way to detect duplicates and reclaim that space.
* The cache is per-volume, because that was the simplest way to implement it. However, this does mean that the cache will get duplicated if a user creates clones on multiple volumes. We could use the GVFS.Service to coordinate and reuse an existing cache from a different volume.
* It may make sense to repack loose blobs into packfiles now that we have the midx feature

**Comment by piranna** [comment]
> The .gvfsCache has no eviction policy, so it will just grow indefinitely. We should think about a good eviction policy, especially for blobs.

As I sugested at https://github.com/Microsoft/GVFS/issues/46, I would remove the less recently used files when a cache size limit is reached, and this limit could be also the full hard disk partition (or user quota) where GVFS is being used. This would allow to use GVFS as a versioned remote filesystem, using the local one as a cache of the remote one.

**Comment by derrickstolee** [comment]
#492 includes a design discussion about how to do maintenance on the shared object cache.

The item listed in this issue that is not covered by that design is the per-volume cache problem.

**Comment by derrickstolee** [comment]
#640 cleans up loose objects.

#635 cleans up pack-files.

Not marking as closed yet, as there is something to investigate further.

**Comment by derrickstolee** [comment]
Current status:

#657 removed the `PackfileMaintenanceStep` from the scheduler. It needs to be re-added after a future release. First, #683 must be merged (and possibly released).
