### ISSUE TITLE
NoReminderForLeftOverDownloads test occasionally fails

### ISSUE THREAD

**Issue by wilbaker** [microsoft/VFSForGit#852]
```
Errors, Failures and Warnings

1) Failed : GVFS.FunctionalTests.Tests.EnlistmentPerFixture.UpgradeReminderTests.NoReminderForLeftOverDownloads()
  Expected: False
  But was:  True
   at GVFS.Tests.Should.ValueShouldExtensions.ShouldEqual[T](T actualValue, T expectedValue, String message) in C:\agent\_work\10\s\GVFS\GVFS.Tests\Should\ValueShouldExtensions.cs:line 34
   at GVFS.Tests.Should.ValueShouldExtensions.ShouldBeFalse(Boolean actualValue, String message) in C:\agent\_work\10\s\GVFS\GVFS.Tests\Should\ValueShouldExtensions.cs:line 16
   at GVFS.FunctionalTests.Tests.EnlistmentPerFixture.UpgradeReminderTests.VerifyServiceRestartStopsReminder() in C:\agent\_work\10\s\GVFS\GVFS.FunctionalTests\Tests\EnlistmentPerFixture\GVFSUpgradeReminderTests.cs:line 149
   at GVFS.FunctionalTests.Tests.EnlistmentPerFixture.UpgradeReminderTests.NoReminderForLeftOverDownloads() in C:\agent\_work\10\s\GVFS\GVFS.FunctionalTests\Tests\EnlistmentPerFixture\GVFSUpgradeReminderTests.cs:line 61
```

https://gvfs.visualstudio.com/ci/_build/results?buildId=7376

I marked this build run as retained.

**Comment by jeschu1** [comment]
Another example: https://gvfs.visualstudio.com/ci/_build/results?buildId=7413

**Comment by jamill** [comment]
This might be addressed by #855

**Comment by wilbaker** [comment]
Just hit this again on this build:

https://gvfs.visualstudio.com/ci/_build/results?buildId=7780

And I confirmed my branch (which has only Mac kernel changes) has the fix for #855 in it.

**Comment by wilbaker** [comment]
@alameenshah @jamill FYI - Re-opening this issue.

**Comment by jeschu1** [comment]
I'm hitting it to as an FYI

**Comment by wilbaker** [comment]
@alameenshah I just hit this again:

```
2) Failed : GVFS.FunctionalTests.Tests.EnlistmentPerFixture.UpgradeReminderTests.NoReminderForLeftOverDownloads()
  Expected: True
  But was:  False
   at GVFS.Tests.Should.ValueShouldExtensions.ShouldEqual[T](T actualValue, T expectedValue, String message) in C:\agent\_work\8\s\GVFS\GVFS.Tests\Should\ValueShouldExtensions.cs:line 34
   at GVFS.Tests.Should.ValueShouldExtensions.ShouldBeTrue(Boolean actualValue, String message) in C:\agent\_work\8\s\GVFS\GVFS.Tests\Should\ValueShouldExtensions.cs:line 10
   at GVFS.FunctionalTests.Tests.EnlistmentPerFixture.UpgradeReminderTests.VerifyServiceRestartStopsReminder() in C:\agent\_work\8\s\GVFS\GVFS.FunctionalTests\Tests\EnlistmentPerFixture\GVFSUpgradeReminderTests.cs:line 232
   at GVFS.FunctionalTests.Tests.EnlistmentPerFixture.UpgradeReminderTests.NoReminderForLeftOverDownloads() in C:\agent\_work\8\s\GVFS\GVFS.FunctionalTests\Tests\EnlistmentPerFixture\GVFSUpgradeReminderTests.cs:line 64
```

https://gvfs.visualstudio.com/ci/_build/results?buildId=8542

**Comment by wilbaker** [comment]
Just hit this again here:

https://gvfs.visualstudio.com/ci/_build/results?buildId=9260

**Comment by jrbriggs** [comment]
@alameenshah the issue here is the test methodology.

The upgrade message randomly fires 10% of the time a Git command is run. So for one run of a Git command, 90% of the time it will not fire. We check the output of 50 commands for the upgrade message. 1-(90%^50)=99.48% of the time it will not fire, which means this test gives a false negative result 0.52% of the time.

We either need a way to configure the percentage of time the message is shown (should be 100% under test), or we need to remove any test depending on the `ReminderMessagingEnabled` helper function.

/cc @jamill @wilbaker

**Comment by wilbaker** [comment]
> We either need a way to configure the percentage of time the message is shown (should be 100% under test), or we need to remove any test depending on the ReminderMessagingEnabled helper function.

Another option might be to drive the upgrade message based on the LastWriteTime of "HighestAvailableVersion" marker file.  For example, if it's been more than one hour since the LastWriteTime of the marker file display the upgrade message and update the file's LastWriteTime.

The functional tests could then set the last write time to be more than an hour ago to ensure the upgrade message is always displayed.

This change would result in the hooks hitting the disk more often, and so we'd need to do some perf tests and see if there is a noticeable impact.

**Comment by jrbriggs** [comment]
Interesting idea, @wilbaker, but at that point, should we move that test into unit tests since we would no longer be testing that the feature functions end-to-end?

**Comment by wilbaker** [comment]
> should we move that test into unit tests since we would no longer be testing that the feature functions end-to-end

I think there would still be value in using the functional tests to validate that the service does the right thing end-to-end.  We'd just need to tweak how we're performing the validation:

- `VerifyUpgradeVerbStopsReminder` -> `VerifyUpgradeVerbDeletesUpgradeMarkerFile`
- `VerifyServiceRestartStopsReminder` -> `VerifyServiceRestartDeletesUpgradeMarkerFileWhenUpToDate`

Today the above methods have the same issue you identified, but in reverse.  They could miss the service failing to cleanup the marker file (because the hooks randomly decided to not display the message).

With the change I suggested above we could update the `CreateUpgradeAvailableMarkerFile` helper method to create a marker file with a LastWriteTime 1 hour+ in the past, and that should allow us to avoid failure the failure in `ReminderMessagingEnabled`.  This change would also allow us to remove the code that calls `git status` in a loop and so the tests should speed up too.

```
private void VerifyServiceRestartStopsReminder()
{
    // Create an upgrade marker file that appears to be very old
    this.CreateUpgradeAvailableMarkerFile();

    // No need to loop, upgrade reminder is guaranteed with a single call to git 
    this.ReminderMessagingEnabled().ShouldBeTrue("Upgrade marker file did not trigger reminder messaging");
...
```

**Comment by jeschu1** [comment]
Hit it today.  Perhaps this one is worth prioritizing @jrbriggs?

**Comment by derrickstolee** [comment]
> The upgrade message randomly fires 10% of the time a Git command is run. So for one run of a Git command, 90% of the time it will not fire. We check the output of 50 commands for the upgrade message. 1-(90%^50)=99.48% of the time it will not fire, which means this test gives a false negative result 0.52% of the time.

This math is correct for the method `ReminderMessagingEnabled()` failing 1 out of 200 times. But that method is also run in six places, so we expect 100% - (99.5% ^ 60) = 2.97% build failures.

**Comment by jrbriggs** [comment]
>This math is correct for the method ReminderMessagingEnabled() failing 1 out of 200 times. But that method is also run in six places, so we expect 100% - (99.5% ^ 60) = 2.97% build failures.

Oh, great point. Thanks for the fix!
