### ISSUE TITLE
Just Idea, OneDrive + GVFS

### ISSUE THREAD

**Issue by quangkieu** [Microsoft/VFSForGit#860]
As I understand that Onedrive only allow symlink on the same system/machine and not allow symlink to a remote system/machine. I wonder if I could set up a repo on remote system then virtual fetch it using GVFS for Onedrive to back it up. I hope that would overcome the remote system check? Then again it I wonder about connection issue...

**Comment by jrbriggs** [comment]
I'm sorry, @quangkieu. I don't understand the problem. Can you explain your scenario?

**Comment by jrbriggs** [comment]
Closing this to keep the issue list healthy. @quangkieu please reopen if you can explain that scenario a different way.

**Comment by quangkieu** [comment]
Sure Briggs. So for example, I has OneDrive root folder, but I would then add another folder not in root to be backup by OneDrive, I would then create a symlink in OneDrive root to that folder. But from my search, OneDrive only work with symlink target to local system. I wonder if I could using VFS or its brother ProjFS to overcome that limit. Or maybe there is other limit on OneDrive?
