### ISSUE TITLE
`gvfs upgrade` can fail if its background processes are launched inside a repo

### ISSUE THREAD

**Issue by wilbaker** [Microsoft/VFSForGit#863]
We've seen a report of `PostInstall.bat` failing when it calls out to `git`:

```
---------------------------
pre-command.exe - Application Error
---------------------------
The application was unable to start correctly (0xc000ce01). Click OK to close the application. 
---------------------------
```

0xc000ce01 is returned by ProjFS when trying to read a non-existent file from inside the repo, and this is what I saw happening the ProjFS logs:

```
[2]1440.2060::02/27/2019-10:09:10.070 [prjflt] ERROR: NTSTATUS=C000CE01: [<root>\src\MSVCP140.dll] Options = 0x00200000 0x00000001(OPEN)
[3]1440.2254::02/27/2019-10:09:10.070 [prjflt] ERROR: NTSTATUS=C000CE01: [<root>\src\VCRUNTIME140.dll] Options = 0x00200000 0x00000001(OPEN)
```

To avoid this issue the upgrade processes should be run from a well known location outside of the repos (e.g. in `InvokeGitOutsideEnlistment` we use Environment.SystemDirectory, see https://github.com/Microsoft/VFSForGit/blob/2917f18d524d95fbb9454a299e0ba5a6f43591b6/GVFS/GVFS.Common/Git/GitProcess.cs#L801)

**Comment by jrbriggs** [comment]
Reactivating to track port to M147
