### ISSUE TITLE
Upgrader: handle  not being able to find git installation more gracefully

### ISSUE THREAD

**Issue by jamill** [Microsoft/VFSForGit#864]
Upgrader should more gracefully handle errors when creating a tracer. Currently, if the tracer is unable to find the local git installation, it will throw an error which will crash the upgrade command.

This scenario should be handled more gracefully.

**Comment by jeschu1** [comment]
Let's include a timestamp in the handling.  

This way we can see if upgrade has a git installation in progress.  I don't think this is the case here, but I can see a user hitting this exception if they ran 'git upgrade' in two separate promps on the same machine around the same time.  Never the less, a timestamp would be helpful in root causing issues.
