### ISSUE TITLE
Mac: Test HandleVnodeOperation and Verify Message Sent

### ISSUE THREAD

**Issue by jeschu1** [Microsoft/VFSForGit#912]
We want to be able to test:
HandleVnodeOperation -> Verify the TrySendRequestAndWaitForResponse

**Comment by pmj** [comment]
Note that my recent PRs #909 and #910 are in this area, so it's probably worth being aware of the changes there as long as they aren't merged to avoid stepping on each others' toes too much and having to rework stuff.
