### ISSUE TITLE
Add a netXX folder to GVFS.ProjFS nuget packages (required for <PackageReference>)

### ISSUE THREAD

**Issue by sanoursa** [Microsoft/VFSForGit#93]
Right now the package just has a `lib\x64` folder, which is not the correct pattern.

**Comment by wilbaker** [comment]
This has been fixed in the official ProjFS nuget.org feed:

https://www.nuget.org/packages/Microsoft.Windows.ProjFS/

VFS for Git started consuming packages from this feed with #885
