### ISSUE TITLE
Uncertainty

### ISSUE THREAD

**Issue by Korporal** [Microsoft/VFSForGit#931]
This whole offering is unclear to me, despite trying to follow progress on this for almost a year, I still have no idea if this has been officially released as a first class, non-beta product by Microsoft. 

The site linked to (by this repo's home page) take us here:

https://vfsforgit.org/

Then on that site clicking "GET STARTED" on the left of the page takes us right back here:

https://github.com/Microsoft/VFSForGit

This is pretty unhelpful, just a circular link!

So - is this a first class fully supported product offering that's passed a whole slew of tests or is it still beta or release candidate grade?

The "DOWNLOAD FOR WINDOWS" link also takes us right back to this repo home!

It seems that that DOWNLOAD FOR WINDOWS should _actually_ take us here:

https://github.com/Microsoft/VFSForGit/releases

But then we see two .EXE links, one **Git-2.20.1....exe** and the other **SetupGVFS....exe** but _which_ of these should a Windows developer install?

Also - once downloaded and installed should we delete our local repos and re-clone them? or what?

Thanks

**Comment by jrbriggs** [comment]
VFS for Git is currently in production inside Microsoft, underpinning the Windows OS repository and other very large repositories inside Microsoft. It is offered to the public as-is.

Your question about what to install is answered in the readme: https://github.com/Microsoft/VFSForGit#installing-vfs-for-git

Your question about how to experiment is also answered in the readme: https://github.com/Microsoft/VFSForGit#trying-out-vfs-for-git

Good feedback about the circular links between the readme and the repo. We'll look at cleaning that up.

I'm closing this out as I believe the questions in the issue have been answered. Please reopen if you have followups.
