### ISSUE TITLE
"installer: Error - Quit these processes and try again - GVFS.Mount." in Mac functional test run

### ISSUE THREAD

**Issue by pmj** [Microsoft/VFSForGit#938]
Build https://dev.azure.com/mseng/AzureDevOps/_build/results?buildId=8883240 encountered this error during the "Install Product" phase. I suspect this was something the previous test run didn't clean up properly? Should we `pkill GVFS.Mount` at the beginning of a functional test run?

**Comment by nickgra** [comment]
I made that change to the build definitons so we should be in a healthy state now. Requeuing a bunch of failed builds.
