### ISSUE TITLE
Approving/Rejecting credentials is not passing useHttpPath config

### ISSUE THREAD

**Issue by turbonaitis** [Microsoft/VFSForGit#948]
When we call `git credential fill`, we add `-c credential.useHttpPath=true`
https://github.com/Microsoft/VFSForGit/blob/master/GVFS/GVFS.Common/Git/GitProcess.cs#L272
While we simply call `git credential approve` and `git credential reject`, without this parameter
https://github.com/Microsoft/VFSForGit/blob/master/GVFS/GVFS.Common/Git/GitProcess.cs#L198
https://github.com/Microsoft/VFSForGit/blob/master/GVFS/GVFS.Common/Git/GitProcess.cs#L182

Because of this, git removes the http path part, before calling the git credential helper
https://github.com/Microsoft/git/blob/vfs-2.20.1/credential.c#L97

This causes interesting behavior, depending on configured credential helper.
This could cause #916 

In general, we should probably not always force `useHttpPath` to `true`, but either always respect whatever is configured in the git config, or at least give a configurable option to respect that.

**Comment by jamill** [comment]
Addressed with #939
