### ISSUE TITLE
VFS for Git should show platform-native notifications

### ISSUE THREAD

**Issue by jrbriggs** [microsoft/VFSForGit#958]
In certain instances it would be useful to show platform-native notifications. For example, when an update is available.

**Comment by nickgra** [comment]
@jrbriggs @alameenshah Should we split this into 2 work items? One for the macOS part and one for the Windows part?

**Comment by wilbaker** [comment]
@alameenshah is this work item complete?

**Comment by wilbaker** [comment]
Didn't mean to close this yet!

**Comment by alameenshah** [comment]
Notifications available on both Win & Mac. Closing.
