### ISSUE TITLE
Mac: Collect real vnode addresses for hash function and table size optimization

### ISSUE THREAD

**Issue by wilbaker** [microsoft/VFSForGit#974]
See discussion in #715 and related issue #611.

This issue is to:

- Optimize the hash function used with the vnode cache
- Optimize the table size and load factor

From @pmj in [a comment on 715](https://github.com/Microsoft/VFSForGit/pull/715#discussion_r265616098):

> Do you know of any tricks we could use for determining their size or potential breaks to our hashing algorithm?

I'll have to check if we can get access to the settings for the zone allocator's vnode zone via public APIs. If not, we'd have to look at the low 12 bits of a bunch of vnode pointers, from those it should be pretty easy to infer, within some reasonable bounds anyway.

> @jeschu1, @pmj if you know of hashing algorithms that might be better suited for our scenario please let me know.

Not off the top of my head, but hashing pointer values is a pretty common thing to do, so there must be some very robust implementations out there. I seem to remember Google publishing some research results on hash tables a while back, that might include something on this topic.

Also highly relevant: table size strategy. A function might be a good hash function with power-of-2 table sizes, but bad for other sizes, or good for prime-sized tables but bad for others. So we might want to revisit the `2 * desiredvnodes` decision and amend that to e.g. `NextPrimeLargerThan(desiredvnodes)` or `RoundUpToPow2(desiredvnodes)`.

Whatever function/size strategy we decide to try, I think we should gather one or more data sets of real vnode addresses via a special version of the kext that logs them all, and then look at collision rates. Especially because there are definite patterns to vnode addresses, they are most certainly not random.

_From a [second discussion](https://github.com/Microsoft/VFSForGit/pull/715#discussion_r265982401):_

Note that you could use the base-2 logarithm function we use for computing time buckets in the perf tracer to fairly easily get the next-highest power of 2 if you prefer. Also, in the worst case you could end up with just over 25% load factor with the current algorithm (if expectedVnodeCount is only slightly larger than a power of 2). With a good hash function, aiming for 50-80% is probably more appropriate. So perhaps get the next largest power of 2 and only double the capacity if expectedVnodeCount is more than 80% of that power of 2?

**Comment by jrbriggs** [comment]
Closing this now since I don't want to take any action here. We'll revisit if we find a perf problem.
