### ISSUE TITLE
Make launchd plists more readable

### ISSUE THREAD

**Issue by alameenshah** [Microsoft/VFSForGit#979]
Suggested format - 

<img width="679" alt="Screen Shot 2019-03-29 at 8 33 22 AM" src="https://user-images.githubusercontent.com/378580/55232944-64ba0880-51fd-11e9-9c15-0b954d4526f0.png">

**Comment by nickgra** [comment]
@pmj Do you have any opinion on the formatting of .plist files? Most of the projects I've worked on have kept the formatting as we have it rather than the proposed example, but I'm sure you have worked with a wider set of applications than I have.

**Comment by pmj** [comment]
Depends if you plan to edit them with Xcode’s plist editor or not. Xcode puts each key and each value on its own line, with the same level of indentation. I normally leave it like that if I do edit a plist by hand.

**Comment by jrbriggs** [comment]
Low priority, not worth spending cycles on this.
