### ISSUE TITLE
Rename the .gvfs folder

### ISSUE THREAD

**Issue by chrisd8088** [microsoft/VFSForGit#987]
This is a proposed change relating to #72 and an addition to the list of issues which follow from that decision (e.g., #130, #131, #132, etc.)

On Linux, the existence of a [GVfs](https://wiki.gnome.org/Projects/gvfs) `.gvfs` folder, as created by the GNOME Virtual file system, precludes the use of the directory with VFSForGit; the `gvfs clone` operation fails with `You can't clone inside an existing GVFS repo` in the [`CheckNotInsideExistingRepo()`](https://github.com/Microsoft/VFSForGit/blob/master/GVFS/GVFS/CommandLine/CloneVerb.cs#L456) method.

For both this reason, and to fully disambiguate the VFSForGit project from GVfs, it would be preferable to use a different folder name for VFSForGit's metadata, such as `.vfsforgit`.

**Comment by jrbriggs** [comment]
We have some internal teams that key off the existence of a `.gvfs` folder on Windows. However, that is not true of either macOS or Linux. We could go ahead and move those platforms, and Windows could follow at its leisure, with a bit of refactoring. I think we've generally been good about not hardcoding .gvfs, I only see a few places in the codebase. We could pull that into the Platform.

Thoughts @chrisd8088 @wilbaker ?

**Comment by wilbaker** [comment]
> We could go ahead and move those platforms

I agree and I think the sooner we can do this on Mac the better.  We don't want any Mac tools to start taking a dependency on `.gvfs`.

> Windows could follow at its leisure, with a bit of refactoring

I agree here as well.  I'm not sure that we'll be able to remove the `.gvfs` folder on Windows completely, but we could leave an empty `.gvfs` folder next to `.vfsforgit` on Windows for the tools that need it.

You're right that there's no urgency for Windows, if we move the folder name into the platform we can continue using `.gvfs` on Windows until we're ready to migrate it.

/ cc: @nickgra to confirm if any Mac tools on his team have taken a dependency on the `.gvfs` folder.

**Comment by chrisd8088** [comment]
Thanks for looking at this!  If you're able to tackle it sooner rather than later, that's fantastic, and of course I expected there would be challenges with the Windows platform, in particular.

**Comment by nickgra** [comment]
> You're right that there's no urgency for Windows, if we move the folder name into the platform we can continue using .gvfs on Windows until we're ready to migrate it. 
@nickgra to confirm if any Mac tools on his team have taken a dependency on the .gvfs folder.

My team is building some tools that we expect to run on Windows and macOS but I believe they key off of an environment variable that another script sets. That script uses the `.gvfs` folder to determine if they're running in a VFS4G clone, it doesn't actually look into the folder, only that it exists. 

Do we know if any tools owned by customers are actually navigating into the `.gvfs` folder vs just keying off of it existing? The empty `.gvfs` folder would work great for my team's tools, so I'd encourage us to make that change ASAP.

**Comment by wilbaker** [comment]
>That script uses the .gvfs folder to determine if they're running in a VFS4G clone, it doesn't actually look into the folder, only that it exists.

Is that a Windows only script, or does it run on Mac as well?

**Comment by nickgra** [comment]
I talked to some people offline, it turns out our tools key off the `.git` folder existing. Therefore, don't worry about our tools when making this change :)

**Comment by kivikakk** [comment]
I've put some WIP up at #1084.
